# -*- coding: utf-8 -*-
"""
Course 02 · 4편 '챗봇·RAG·MCP' — Anthropic 공식 + 도구 공식 자료
==============================================================
대상: IT 담당자 + 사내 챗봇·RAG 도입 의사결정자 (초보자 톤 유지)
분량: 1강(60) + 2강(60) + 3강(60) = 총 180분, 32 슬라이드

작성 원칙 (1·2·3편 v2와 동일):
- 모든 도구 정보는 공식 GitHub·문서 인용
- 가변층(가격·UI 디자인) vs 불변층(아키텍처·RAG·MCP 원리) 명시
- 초보자 톤 — 전문용어 매번 풀이
- 슬라이드당 노트 2,500자+ (LV8 수준)
- 매 슬라이드 ‘다음 주 월요일 액션’

notes 태그: SAY / STORY / Q / DO / TIP / NOTE / BRIDGE
"""

META = {
    "course": "Course 02 · 사내 AI 구축·운영 종합 가이드",
    "part": "4편", "part_title": "챗봇·RAG·MCP",
    "lessons": "1강 사내 챗봇 UI 4종 + 2강 RAG 4계층 + 3강 MCP",
    "audience": "IT 담당자 + 사내 챗봇·RAG 도입 의사결정자",
    "duration": "1강(60분) + 2강(60분) + 3강(60분) = 총 180분",
    "url": "visionc.co.kr/ai-solution/academy/build-ai",
    "password": "visioncDown (대소문자 구분)",
    "format": "사내 출강 / 워크숍",
    "subtitle": "직원이 매일 쓰는 화면 + 사내 문서 학습 + 외부 시스템 연결",
    "sources_note": "본 자료의 도구 정보는 각 도구 공식 GitHub·문서(Open WebUI·Dify·LibreChat·AnythingLLM·LlamaIndex·Qdrant·Anthropic MCP) 인용. 한국 사례는 명시. RAG 4계층 + PII Footer는 Anthropic 'Self-Service Data Analytics' 공식 사례.",
}

# 자주 인용되는 출처 단축 표기
S_DATA = "Anthropic 'How Anthropic enables self-service data analytics with Claude'"
S_COWORK = "Anthropic 'Deploying Claude across the enterprise with Claude Cowork'"
S_MCP = "Anthropic 'Introducing the Model Context Protocol' (2024-11)"
S_AGENTS_ENT = "Anthropic 'Building AI agents for the enterprise'"
S_OWEBUI = "Open WebUI 공식 GitHub"
S_DIFY = "Dify 공식 (langgenius/dify) GitHub"
S_LIBRECHAT = "LibreChat 공식 GitHub"
S_ANYTHINGLLM = "AnythingLLM (Mintplex Labs) 공식"
S_LLAMAINDEX = "LlamaIndex 공식 문서"
S_QDRANT = "Qdrant 공식 문서"
S_LANGCHAIN = "LangChain 공식 문서"

SLIDES = [
    # ============================ 1강 ============================
    dict(no=1, lesson="1강", cat="INTRO · TITLE", lay="title",
         headline="사내 챗봇 UI 4종",
         sub="1강 — Open WebUI · Dify · LibreChat · AnythingLLM",
         bullets=[], time="3분 · 시작·환영",
         notes=[
            ("SAY", "“반갑습니다. 사내 AI 구축·운영 가이드 4편 ‘챗봇·RAG·MCP’입니다. 3편이 ‘엔진(모델 + 추론)’이었다면 4편은 ‘사용자가 만나는 화면 + 사내 문서 학습 + 외부 시스템 연결’입니다.”"),
            ("SAY", "“4편 3강 구성. 1강 ‘사내 챗봇 UI 4종’ — Open WebUI, Dify, LibreChat, AnythingLLM. 2강 ‘RAG 4계층’ — 사내 문서 학습. 3강 ‘MCP’ — Model Context Protocol, 외부 시스템 연결. 180분 후 ‘사내 직원이 매일 쓰는 도구 1페이지 결정’.”"),
            ("SAY", "“4편 약속 — 4편은 ‘사용자가 실제 만지는 부분’입니다. ‘기술’보다 ‘사용자 경험’이 핵심. 본 강좌가 ‘기술 자료’이지만 ‘직원이 좋아하는 도구가 좋은 도구’ 관점 유지.”"),
            ("Q", "도입 질문 1: “ChatGPT 사내 사용해본 분 손?” → 보통 다수. → ‘좋아요. ChatGPT가 ‘외부 클라우드 + 무료 데모’입니다. 우리 회사 도입은 ‘사내 자체 + 회사 문서 학습 + 사내 시스템 연결’ — 4편이 그 셋을 만듭니다.’"),
            ("Q", "도입 질문 2: “3편 ‘Qwen 7B + Ollama + Open WebUI’ 결정 분?” → 보통 다수. → ‘좋아요. Open WebUI를 4편 1강에서 더 자세히. + 다른 3개 옵션도 비교.’"),
            ("NOTE", "★ 강사 핵심 배경지식 — 4편 청중 구성 변화: 1~3편이 ‘IT 담당자 + 의사결정자’ 중심이었다면 4편은 ‘사용자 경험’ 측면이 커서 ‘부서장 + 직원 챔피언’ 청중이 늘어남. 대응 — (1) UI 스크린샷 적극. (2) ‘직원이 쉽게 쓸 수 있나’ 관점. (3) 기술보다 ‘체감’."),
            ("NOTE", "강사 배경지식 — 4편 인용 출처 (1차): (1) Open WebUI 공식 GitHub. (2) Dify (langgenius) 공식. (3) LibreChat 공식. (4) AnythingLLM (Mintplex Labs). (5) LlamaIndex 공식 문서. (6) Qdrant 공식. (7) LangChain 공식. (8) Anthropic 'Self-Service Data Analytics' (RAG 4계층 + PII Footer). (9) Anthropic MCP 공식 발표. (10) Anthropic 'Building AI agents for the enterprise'."),
            ("NOTE", "강사 배경지식 — 4편 60분 시간 배분 (1강): 0~3분 인사. 3~6분 학습목표. 6~10분 3편 복습. 10~14분 ‘왜 사내 UI’. 14~22분 4종 한눈에. 22~46분 각 도구 디테일(각 5~6분). 46~52분 선택 매트릭스. 52~58분 실습. 58~60분 마무리."),
            ("TIP", "강사 함정 — ‘UI는 디자인 취향’ X: 디자인보다 ‘기능·확장성·운영’이 결정 기준. 청중에게 ‘예쁜 UI’ 보다 ‘오래 쓸 도구’ 메시지."),
            ("BRIDGE", "“학습 목표 빠르게.”"),
         ]),
    dict(no=2, lesson="1강", cat="OBJECTIVES", lay="bullets",
         headline="60분 후, 이 3가지를 한다",
         sub="",
         bullets=[
            "① 사내 챗봇 UI 4종(Open WebUI·Dify·LibreChat·AnythingLLM)의 차이를 안다",
            "② 우리 회사 ‘시작 UI + 6개월 후 UI’ 2단계 결정한다",
            "③ ‘우리 회사 UI 결정서 1페이지’ 워크시트 완성"],
         time="3분 · 학습목표",
         notes=[
            ("SAY", "“60분 후 셋. 첫째, ‘4종 UI 차이’ 명확. 동료에게 ‘우리는 OO으로, OO은 6개월 후 검토’ 설명 가능.”"),
            ("SAY", "“둘째, ‘2단계 결정’. 처음부터 모든 기능 갖춘 UI X. ‘시작은 단순’, ‘본격은 풍부’ 2단계. Open WebUI 시작 → 6개월 후 Dify 검토 같은 흐름.”"),
            ("SAY", "“셋째, 워크시트 1페이지. 4편 1·2·3강 끝나면 ‘UI + RAG + MCP’ 3장 결정서 완성.”"),
            ("NOTE", "★ 강사 핵심 배경지식 — 1강 성공 기준: 청중이 ‘우리 회사가 어떤 UI 깔지’ 결정. ‘기술 깊이’가 아니라 ‘선택 가능’."),
            ("NOTE", "강사 배경지식 — 4종 위치: (1) Open WebUI — 한국 자체 호스팅 시작 표준. (2) Dify — ‘노코드 워크플로우’ 빌더. (3) LibreChat — 다중 모델 동시 운영. (4) AnythingLLM — 문서 중심. 4가지가 비슷한 영역 — 단 ‘세부 강점’ 차이."),
            ("TIP", "강사 진행 팁 — 학습 목표 3분 안에 끝."),
            ("BRIDGE", "“3편 복습 + 4편 위치 빠르게.”"),
         ]),
    dict(no=3, lesson="1강", cat="RECAP · PART 3", lay="bullets",
         headline="3편 복습 — 모델 + 추론 결정",
         sub="🟦 불변층 — 3편의 5개 핵심",
         bullets=[
            "1강 — 무료 LLM 5종 (Llama·Qwen·Mistral·DeepSeek·GPT-OSS) → 1순위 결정",
            "2강 — 한국어 특화 4종 (Solar·EXAONE·KULLM·Bllossom) → 도메인 결정",
            "3강 — 추론 엔진 4종 (Ollama·vLLM·llama.cpp·TGI) + 양자화 Q4 표준",
            "★ 추천 시작 셋 — Qwen 2.5 7B + Ollama + Q4 + Open WebUI",
            "★ 4편 위치 — Open WebUI ‘디테일 + 다른 옵션 비교’"],
         time="4분 · 3편 복습",
         notes=[
            ("SAY", "“4편 본문 들어가기 전 3편 복습 30초씩.”"),
            ("SAY", "“첫째, 1강 무료 LLM 5종. Llama·Qwen·Mistral·DeepSeek·GPT-OSS. 첫 시작 권장 Qwen 7B.”"),
            ("SAY", "“둘째, 2강 한국어 특화 4종. Solar·EXAONE·KULLM·Bllossom. 무료 + 자유 — Bllossom 8B.”"),
            ("SAY", "“셋째, 3강 추론 엔진 4종. Ollama·vLLM·llama.cpp·TGI. 시작 — Ollama. 본격 — vLLM. 양자화 Q4 표준.”"),
            ("SAY", "“추천 시작 셋 — Qwen 7B + Ollama + Q4 + Open WebUI. 한국 자체 호스팅 표준.”"),
            ("SAY", "“4편 위치 — 추천 셋의 마지막 ‘Open WebUI’를 디테일 + 다른 UI 옵션 비교. 4편 끝나면 ‘UI 결정 = 풍부한 답’.”"),
            ("NOTE", "★ 강사 핵심 배경지식 — 3편을 안 들은 청중 대응: 4편만 듣는 ‘부서장·직원 챔피언’ 청중. 이 슬라이드 + ‘3편 디테일은 visionc 사이트에서’ 안내."),
            ("NOTE", "강사 배경지식 — 4편이 부서장에게 의미: 1~3편이 ‘IT 결정’이었다면 4편은 ‘직원이 매일 쓰는 도구 결정’. 부서장이 직원 챔피언 5명과 함께 ‘우리 부서 어떤 UI’ 결정 가능."),
            ("Q", "도입 질문: “Open WebUI 1주 안 설치하신 분?” → 보통 1~2명. → ‘좋아요. 4편 끝나면 ‘이번 주 안 설치 가능’ 동기.’"),
            ("TIP", "강사 진행 팁 — 4분 시간 배분: 0~2분 5개 핵심 30초씩. 2~3분 추천 셋. 3~4분 4편 위치."),
            ("BRIDGE", "“복습 끝. 본격적으로 — ‘왜 사내 UI 필요한가’.”"),
         ]),
    dict(no=4, lesson="1강", cat="WHY UI", lay="compare",
         headline="왜 사내 챗봇 UI? — ChatGPT 따라 만들기",
         sub="🟦 불변층 — 사용자가 만지는 부분",
         cards=[("UI 없이",
                 "REST API 직접 호출",
                 "Ollama·vLLM이 API 제공. 단 직원이 직접 호출 X. 명령줄·코딩 필요. ‘1명 테스트’만 OK. 사내 보급 불가.",
                 "cyan"),
                ("UI 도구 사용",
                 "Open WebUI·Dify 등",
                 "ChatGPT 같은 ‘대화 화면’. 직원이 ‘챗 입력 → 답’ 즉시. 로그인·권한·이력·파일 첨부 다. 사내 보급의 필수.",
                 "purple")],
         bullets=[], time="5분 · 왜 UI",
         notes=[
            ("SAY", "“1강 본문 1번 — ‘왜 사내 UI 필요한가’입니다.”"),
            ("SAY", "“3편의 추천 셋 — Qwen + Ollama — 깔았다고 끝 X. Ollama는 ‘REST API 제공’. 즉 ‘프로그램이 호출’ 형태. 직원이 직접 호출 못 함.”"),
            ("SAY", "“UI 없이 사용 — 명령줄·코딩 필요. ‘1명 테스트’만 OK. 50명 사내 보급 — 불가능.”"),
            ("SAY", "“UI 도구 사용 — ChatGPT 같은 ‘대화 화면’. 로그인·권한·이력·파일 첨부 다 포함. 직원이 ‘챗 입력 → 답’ 즉시. ‘50명 사내 챗봇’ 운영 가능.”"),
            ("SAY", "“원칙 — 자체 호스팅 본격 운영 시 ‘UI 필수’. ‘Ollama만 깔고 끝’ 한국 회사 거의 X.”"),
            ("STORY", "사내 UI 도입 트렌드 (강사 대응용). 2023년 ChatGPT 충격 → 한국 회사 ‘ChatGPT 사용 정책’ 검토 → 2024년 ‘사내 자체 챗봇’ 도입 시작. ‘UI = ChatGPT 비슷한 모양’ 기대 형성. Open WebUI·Dify·LibreChat 같은 무료 도구 등장으로 진입 장벽 낮음."),
            ("STORY", "Open WebUI 도입 사례 (강사 대응용). 한국 자체 호스팅 약 60% Open WebUI 채택. 이유 — (1) ChatGPT 비슷한 UI. (2) Docker 1줄 설치. (3) Ollama 자동 연결. (4) RAG·MCP 지원. (5) 한국어 UI 완성도. ‘1주 안 사내 50명 챗봇’ 가능."),
            ("STORY", "사용자 적응 비용 (강사 대응용). ‘ChatGPT 익숙한 직원’ → ‘사내 챗봇’ 전환 시 학습 비용 거의 0 (UI 비슷). 단 ‘UI 너무 다름’ — 직원 거부감 + 사용률 낮음. ‘ChatGPT 같은 UI’가 도입 성공의 핵심."),
            ("NOTE", "★ 강사 핵심 배경지식 — UI 결정의 4대 기준: (1) ChatGPT 비슷한가 — 사용자 적응. (2) 설치·운영 쉬운가 — IT 부담. (3) 사내 통합 가능한가 — SSO·LDAP·RBAC. (4) 확장 가능한가 — RAG·MCP·플러그인. 4대 균형이 결정 핵심."),
            ("NOTE", "강사 배경지식 — ‘오픈소스 UI’ vs ‘상용 UI’: 무료 오픈소스 — Open WebUI·LibreChat·AnythingLLM. 상용 — Dify(Enterprise), Botpress, Microsoft Copilot Studio 등. 한국 자체 호스팅 99% 오픈소스. 본 강좌는 오픈소스 중심."),
            ("NOTE", "강사 배경지식 — UI 선택의 ‘과도한 기능 함정’: 초보자 자주 ‘기능 많은 UI’ 선택. 함정 — ‘기능 많음 = 학습 어려움 + 운영 부담 큼’. 처음은 단순 + 6개월 후 확장. ‘Dify 처음부터 도입’ 함정. ‘Open WebUI 시작 → Dify 검토’ 권장."),
            ("Q", "예상 청중 질문 1: ‘UI 꼭 필요한가? 우리 IT가 직접 사용?’ → 답: ‘IT가 직접은 OK. 단 사내 50명+ 보급은 UI 필수. ‘우리 IT만 사용’이면 UI X 가능. ‘직원 전체’면 UI 필수.’"),
            ("Q", "예상 청중 질문 2: ‘사내 UI 자체 개발 vs 오픈소스?’ → 답: ‘오픈소스 권장. 자체 개발 — 비용·시간·유지보수 큼. 오픈소스 — 1주 설치 + 1년 운영. ‘디자인·기능 절대 특수’ 회사만 자체 개발.’"),
            ("Q", "예상 청중 질문 3: ‘ChatGPT 그대로 쓰면?’ → 답: ‘직원이 ChatGPT 외부 클라우드 사용 — 데이터 송신 + 토큰 비용 + 사내 정책. 우리 자체 호스팅은 ‘데이터 사내 + 비용 0 + 정책 통제’. 답은 ‘2개 다’ 가능 — 일반 ChatGPT 허용 + 사내 민감 챗봇.’"),
            ("TIP", "강사 함정 — UI 디자인 자랑 X: ‘기능·확장·운영’ 우선. 디자인은 6개월 운영 후 보완 가능."),
            ("TIP", "강사 진행 팁 — 5분 시간 배분: 0~1분 ‘UI 없이 vs 있으면’. 1~2분 4대 결정 기준. 2~3분 한국 분포. 3~4분 ‘과도한 기능 함정’. 4~5분 청중 질문. ‘사용자 경험’ 강조."),
            ("BRIDGE", "“UI 필요성 봤다면 — 4종 한눈에 비교.”"),
         ]),
    dict(no=5, lesson="1강", cat="4 UI COMPARE", lay="stats",
         headline="★ 4종 사내 챗봇 UI 한눈에",
         sub="🟨 가변층 — 2026.6 시점, 기능 매년 추가",
         stats=[("Open WebUI",
                 "한국 자체 호스팅 1위 · 시작 표준",
                 "GitHub 별 100,000+. Docker 1줄 설치. ChatGPT 비슷한 UI. Ollama 자동 연결. RAG·MCP 지원. 한국어 완성. 무료. 한국 60% 점유."),
                ("Dify",
                 "노코드 워크플로우 빌더",
                 "‘드래그·드롭’ 워크플로우. 챗봇 + 에이전트 + RAG 통합. 무료(자체 호스팅) + 유료(클라우드). 본격 사내 통합 우수."),
                ("LibreChat",
                 "다중 모델 동시 운영",
                 "ChatGPT·Claude·Gemini·로컬 모델 1 UI에서. ‘여러 모델 비교’ 강점. 가족·소그룹 자체 호스팅 인기. 사내 본격은 단순."),
                ("AnythingLLM",
                 "문서 중심 · 워크스페이스 분리",
                 "‘부서별 워크스페이스’ 분리. 문서 RAG 강점. 영업·법무·HR 부서별 분리 자연스러움. 단 사용자 수 많은 운영엔 단순.")],
         bullets=[], time="6분 · 4종 한눈에",
         notes=[
            ("SAY", "“4종 UI 한눈에. 한 표로 결정의 핵심.”"),
            ("SAY", "“Open WebUI — 한국 자체 호스팅 1위. ‘시작 표준’. GitHub 별 100,000+. Docker 1줄 설치. ChatGPT 비슷한 UI. Ollama 자동 연결. 한국어 완성. 한국 점유 약 60%.”"),
            ("SAY", "“Dify — ‘노코드 워크플로우 빌더’. ‘드래그·드롭’으로 챗봇·에이전트·RAG 통합. 본격 사내 통합 시 우수. 무료(자체) + 유료(클라우드 SaaS).”"),
            ("SAY", "“LibreChat — ‘다중 모델 동시 운영’. ChatGPT·Claude·Gemini·로컬 모델 1 UI에서. ‘여러 모델 비교’ 강점. 가족·소그룹 자체 호스팅 인기. 사내 본격은 단순.”"),
            ("SAY", "“AnythingLLM — ‘문서 중심·워크스페이스 분리’. ‘부서별 워크스페이스’ 자연 분리. 문서 RAG 강점. 영업·법무·HR 부서별 자연. 단 사용자 수 많은 운영엔 단순.”"),
            ("SAY", "“핵심 — Open WebUI 시작 권장. 6개월 운영 후 ‘부족’ 확인 시 Dify 갈아탐 또는 추가. AnythingLLM은 ‘문서 중심 회사’ 특수, LibreChat은 ‘여러 모델 동시’ 특수.”"),
            ("STORY", "Open WebUI 공식. 2023 시작. URL: openwebui.com, github.com/open-webui/open-webui. 기존 ‘Ollama Web UI’ 이름이었다가 ‘Open WebUI’로 개명. MIT 라이센스. 무료. 한국어 UI 완성도 높음."),
            ("STORY", "Dify 공식. 2023 중국 회사 ‘LangGenius’ 시작. URL: dify.ai, github.com/langgenius/dify. 자체 호스팅 무료 + 클라우드 SaaS 유료. 한국 도입 — 일부 IT·핀테크 회사. Apache 2.0 라이센스."),
            ("STORY", "LibreChat 공식. URL: librechat.ai, github.com/danny-avila/LibreChat. MIT 라이센스. ChatGPT 클론으로 시작 → 다중 모델 통합. 한국 자체 호스팅 사례 적음 (Open WebUI에 밀림). 단 ‘ChatGPT + Claude 동시’ 원하면 강점."),
            ("STORY", "AnythingLLM 공식. Mintplex Labs 2023 시작. URL: useanything.com, github.com/Mintplex-Labs/anything-llm. MIT 라이센스. ‘문서 중심 챗봇’. 한국 일부 회사 — 법무·컨설팅 같은 ‘부서별 문서’ 운영."),
            ("NOTE", "★ 강사 핵심 배경지식 — ‘4종 외 다른 옵션’: (1) Chatbot UI (mckaywrigley) — 단순 ChatGPT 클론. (2) Lobe Chat — 디자인 우수, 중국발. (3) Big-AGI — 다중 페르소나. (4) Hollama, GPT4All 등. 한국 자체 호스팅 99% 4종 안에서 선택."),
            ("NOTE", "강사 배경지식 — Open WebUI ‘1위’ 이유 4가지: (1) Docker 1줄 설치. (2) Ollama 자동 연결 — IP·포트 X. (3) 한국어 UI 완성. (4) RAG·MCP·플러그인 다. ‘시작 진입장벽 최소 + 기능 풍부’ 균형."),
            ("NOTE", "강사 배경지식 — Dify ‘노코드’의 의미: ‘드래그·드롭’으로 ‘질문 분류 → 검색 → 답 생성’ 흐름 시각화. 일반 PM·기획자도 워크플로우 설계 가능. ‘IT 코딩 없이 챗봇 만들기’ 컨셉. 단 ‘일반 사내 챗봇’엔 과도, ‘본격 통합 챗봇’엔 의미."),
            ("NOTE", "강사 배경지식 — AnythingLLM ‘워크스페이스’의 의미: 챗봇을 부서별 분리. 영업 워크스페이스 = 영업 문서만 학습. 법무 = 법무 문서만. 자연스러운 권한 분리. 본 강좌 9편 보안의 RBAC와 호환. ‘부서별 분리’ 강점."),
            ("Q", "예상 청중 질문 1: ‘우리는 첫 시작 — Open WebUI?’ → 답: ‘맞아요. 90% 한국 자체 호스팅 시작 권장. 6개월 운영 후 추가 검토.’"),
            ("Q", "예상 청중 질문 2: ‘Dify 처음부터?’ → 답: ‘권장 X. 학습 부담 큼. Open WebUI 시작 → 6개월 후 ‘워크플로우 본격 필요’ 확인되면 Dify.’"),
            ("Q", "예상 청중 질문 3: ‘4개 다 동시?’ → 답: ‘권장 X. 1개 운영 안정 후 2번째. 동시 4개 = 운영 부담 4배.’"),
            ("TIP", "강사 함정 — UI 점유율 자세히 X: ‘60% Open WebUI’ 메시지만. 디테일은 변동."),
            ("TIP", "강사 진행 팁 — 6분 시간 배분: 0~1분 4종 한눈에. 1~4분 각 1분씩. 4~5분 ‘Open WebUI 시작’ 메시지. 5~6분 청중 질문."),
            ("BRIDGE", "“4종 한눈에 봤다면 — 각 디테일. 첫 번째 Open WebUI.”"),
         ]),
    dict(no=6, lesson="1강", cat="OPEN WEBUI", lay="bullets",
         headline="Open WebUI — 한국 자체 호스팅 표준",
         sub="🟦 불변층 — 4대 강점 + 🟨 가변층 — 2026.6 기능",
         bullets=[
            "★ Docker 1줄 설치 — 5분에 완료",
            "★ Ollama·vLLM·OpenAI API 모두 자동 연결",
            "★ ChatGPT 비슷한 UI — 직원 적응 0",
            "★ RAG 내장 — 문서 업로드 즉시 사용",
            "★ MCP 지원 (2025) — ERP·메일·DB 연결",
            "★ 한국어 UI 완성도 + LDAP·SSO·OAuth 지원"],
         time="6분 · Open WebUI",
         notes=[
            ("SAY", "“UI 디테일 첫 번째 — Open WebUI. 한국 자체 호스팅 표준.”"),
            ("SAY", "“핵심 — Docker 1줄 설치. ‘docker run ... ghcr.io/open-webui/open-webui:main’. 5분에 완료. http://서버:3000 접속 시 ChatGPT 비슷한 UI.”"),
            ("SAY", "“Ollama·vLLM·OpenAI API 모두 자동 연결. 설정 페이지에서 ‘모델 추가’ — Ollama 모델·OpenAI 키·로컬 vLLM URL 입력 → 즉시 사용.”"),
            ("SAY", "“ChatGPT 비슷한 UI — 직원 적응 0. ‘챗 입력 → 답’ + 이력 + 파일 첨부 + 다중 대화. 추가 — 모델 비교, 프롬프트 라이브러리, 함수 호출, 음성 입력.”"),
            ("SAY", "“RAG 내장 — 문서 업로드 즉시 사용. PDF·DOCX·TXT·웹 페이지 업로드 → 자동 인덱싱 → 챗에서 검색. 2강 RAG 디테일.”"),
            ("SAY", "“MCP 지원 (2025) — Anthropic의 Model Context Protocol. 사내 ERP·메일·DB 같은 외부 시스템 연결. 3강 디테일.”"),
            ("SAY", "“한국어 UI 완성 + LDAP·SSO·OAuth 지원. 한국 회사 사용에 거의 모든 필요 충족.”"),
            ("STORY", "Open WebUI 디테일. URL: docs.openwebui.com. 기능 — (1) 채팅 + 이력. (2) 모델 관리. (3) RAG (문서·웹). (4) 함수 호출(MCP). (5) 사용자 관리(LDAP·OAuth). (6) Pipeline (자체 함수 추가). (7) 음성 입력·출력. ‘ChatGPT + RAG + 권한’ 통합."),
            ("STORY", "Open WebUI 설치 1줄. ‘docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main’. 1줄 5분. 단 GPU 사용 시 추가 옵션."),
            ("STORY", "Open WebUI 한국 사례 (강사 대응용). 카카오·네이버 일부 사내 — 자체 챗봇 일부. 중견 IT 회사 — 사내 챗봇 1위 도구. 스타트업 — ‘1주 안 도입’ 표준. ‘무료 + 1주 + 사내’ 조합으로 압도적."),
            ("NOTE", "★ 강사 핵심 배경지식 — Open WebUI 6가지 일상 기능: (1) 채팅 — ChatGPT 비슷. (2) 모델 전환 — 드롭다운에서 Llama·Qwen·Solar 등 선택. (3) 파일 첨부 — PDF·이미지·문서. (4) 이력 — 대화 자동 저장. (5) 워크스페이스 (2025 신규) — 챗별 그룹화. (6) 프롬프트 관리 — 자주 쓰는 명령 저장."),
            ("NOTE", "강사 배경지식 — Open WebUI ‘설정 페이지’ 디테일: 관리자 페이지에서 — (1) 사용자 관리 + RBAC. (2) 모델 관리. (3) 환경변수·시스템 설정. (4) Pipelines (자체 함수). (5) MCP 서버 연결. (6) RAG 설정 (청크·임베딩). (7) 데이터베이스·백업. 일반 사용자 X 관리자 페이지."),
            ("NOTE", "강사 배경지식 — Open WebUI ‘Pipeline’: 자체 함수 추가 기능. ‘Python 함수 + 외부 API 호출’ 가능. 예 — ‘사내 ERP 매출 조회 함수’, ‘날씨 API 호출’, ‘번역 함수’. MCP 등장 이전부터 가능했던 확장. 본 강좌 6편(하네스)에서 자세히."),
            ("NOTE", "강사 배경지식 — Open WebUI ‘LDAP·SSO·OAuth’: 한국 회사 ‘Active Directory’ 사용 → LDAP 연결. ‘Microsoft 365 SSO’ → OAuth. 직원이 ‘회사 계정으로 자동 로그인’ 가능. 별도 비밀번호 X. 본 강좌 2편 3강 RBAC와 호환."),
            ("Q", "예상 청중 질문 1: ‘Docker 모르는데?’ → 답: ‘Docker 1줄만 외우면 OK. 본 강좌 2편 2강 Docker. 1시간 학습이면 충분.’"),
            ("Q", "예상 청중 질문 2: ‘무료인데 정말 본격 운영 OK?’ → 답: ‘예. 카카오·네이버 같은 대기업도 사용. ‘무료’와 ‘본격 운영 OK’ 둘 다 사실. 단 ‘24/7 운영 부담’은 사내 IT.’"),
            ("Q", "예상 청중 질문 3: ‘LDAP·OAuth 설정 어렵나?’ → 답: ‘설정 1회 1~3시간 + 한국어 가이드 풍부. IT부 1주 안 가능. Microsoft 365 사용 회사는 OAuth 1시간.’"),
            ("TIP", "강사 함정 — Open WebUI 설정 디테일 X: ‘1줄 설치 + 1주 운영’ 메시지. 디테일은 IT부."),
            ("TIP", "강사 진행 팁 — 6분 시간 배분: 0~1분 ‘표준’ 메시지. 1~3분 6대 기능. 3~4분 LDAP·SSO. 4~5분 사례. 5~6분 청중 질문. ‘1주 안 시작’ 동기."),
            ("BRIDGE", "“Open WebUI 봤다면 — 워크플로우 빌더 Dify.”"),
         ]),
    dict(no=7, lesson="1강", cat="DIFY", lay="bullets",
         headline="Dify — 노코드 워크플로우 빌더",
         sub="🟦 불변층 — 워크플로우 + RAG + 에이전트 통합",
         bullets=[
            "★ ‘드래그·드롭’ 노코드 — 코딩 없이 챗봇·에이전트 빌드",
            "★ 워크플로우 — ‘질문 분류 → 검색 → 답’ 흐름 시각화",
            "★ RAG·에이전트·MCP 통합 — 1 도구에서 모두",
            "★ 자체 호스팅(Docker) 무료 + 클라우드 SaaS 유료",
            "★ 한국 도입 — 일부 IT·핀테크 회사 (Open WebUI보다 학습 부담 큼)",
            "★ 강점 — ‘본격 사내 통합 챗봇’ 시 의미. 시작 도구로는 과도"],
         time="6분 · Dify",
         notes=[
            ("SAY", "“UI 디테일 두 번째 — Dify. 중국 회사 LangGenius 발. 노코드 워크플로우 빌더.”"),
            ("SAY", "“핵심 — ‘드래그·드롭’으로 챗봇·에이전트 빌드. 코딩 없이 ‘질문 입력 → 분류 → 검색 → 답’ 흐름 시각화. 일반 기획자·PM도 설계.”"),
            ("SAY", "“기능 — RAG·에이전트·MCP·함수 호출 통합. 1 도구에서 모두. ‘완전한 사내 AI 플랫폼’ 컨셉.”"),
            ("SAY", "“라이센스·가격 — 자체 호스팅 Docker 무료 (Apache 2.0). 클라우드 SaaS 유료 — 월 $59~$1,599. 한국 회사 99% 자체 호스팅 무료.”"),
            ("SAY", "“한국 도입 — 일부 IT·핀테크 회사. Open WebUI보다 사례 적음. 이유 — 학습 부담 큼, 운영 복잡, ‘과도한 기능’ 함정.”"),
            ("SAY", "“강점 — ‘본격 사내 통합 챗봇’ 시 의미. 50명+ 사용 + 부서별 다른 워크플로우 + 외부 시스템 연결 다수. 시작 도구로는 과도.”"),
            ("STORY", "Dify 공식. URL: dify.ai, github.com/langgenius/dify. 2023 LangGenius 창업. Apache 2.0. GitHub 별 60,000+. ‘LangChain의 노코드 버전’ 위치."),
            ("STORY", "Dify 워크플로우 디테일 (강사 대응용). 노드(node) 종류 — (1) Start (질문 받기). (2) LLM (모델 호출). (3) Knowledge Retrieval (RAG). (4) Question Classifier. (5) IF/ELSE 분기. (6) Code (Python). (7) HTTP Request. (8) End. 드래그·드롭 + 연결 = 워크플로우 완성. 시각화 우수."),
            ("STORY", "Dify 한국 사례 (강사 대응용). 일부 핀테크·SaaS 회사 ‘사내 통합 챗봇’. ‘영업 문의 자동 답 + 사내 위키 검색 + 회의 일정 잡기’ 같은 복합 시나리오. ‘본격 사내 챗봇’ 도입의 회사."),
            ("STORY", "Dify vs LangChain 위치 (강사 대응용). LangChain — 개발자용 Python 라이브러리. Dify — 노코드 UI. 본질 비슷 — 둘 다 ‘LLM 워크플로우 빌더’. Dify가 시각화 + 사용자 관리 추가. 본 강좌 6편(하네스)에서 LangChain 더 자세히."),
            ("NOTE", "★ 강사 핵심 배경지식 — Dify ‘과도한 함정’: 초보자 자주 ‘Dify가 노코드라 쉬워 보임’. 함정 — (1) 워크플로우 개념 학습 부담. (2) 노드 20개+ 워크플로우 운영 복잡. (3) 디버깅 어려움. (4) 단순 챗봇엔 과도. 단순 챗봇 시작은 Open WebUI."),
            ("NOTE", "강사 배경지식 — Dify ‘적합 시점’: (1) 사내 50명+ + 부서별 다른 워크플로우. (2) 외부 시스템 통합 다수 (ERP·CRM·메일·DB 등 5개+). (3) ‘질문 분류·자동 답·복합 흐름’ 자주 필요. (4) IT 학습 시간 가능. 4개 다 충족이면 Dify."),
            ("NOTE", "강사 배경지식 — Dify ‘중국 회사’ 우려: LangGenius 중국 회사. 자체 호스팅 시 ‘중국 송신’ X — Docker 사내 실행. 단 클라우드 SaaS 사용은 데이터 송신. 보안 우려 강하면 자체 호스팅."),
            ("NOTE", "강사 배경지식 — Dify Enterprise (유료): 클라우드 SaaS 외에 ‘Enterprise Self-Hosted’ 유료 옵션. SSO·고급 권한·SLA·전담 지원. 본격 대기업 도입 시 검토. 가격 견적."),
            ("Q", "예상 청중 질문 1: ‘Open WebUI vs Dify 결정?’ → 답: ‘시작은 Open WebUI. ‘50명+ + 워크플로우 본격 + 시스템 통합 5개+’ 확인되면 Dify로 갈아탐 또는 추가.’"),
            ("Q", "예상 청중 질문 2: ‘Dify 학습 시간?’ → 답: ‘기본 워크플로우 1주. 본격 운영 3~4주. Open WebUI(1일)에 비해 진입 장벽 큼.’"),
            ("Q", "예상 청중 질문 3: ‘Dify 한국어 UI?’ → 답: ‘완성도 OK. 단 일부 신규 기능은 영어. Open WebUI보다 약간 미흡.’"),
            ("TIP", "강사 함정 — ‘Dify가 더 좋아 보임’ X: ‘좋아 보임 ≠ 우리 회사 적합’. 시작은 단순."),
            ("TIP", "강사 진행 팁 — 6분 시간 배분: 0~1분 ‘노코드 워크플로우’. 1~3분 워크플로우 디테일. 3~4분 적합 시점. 4~5분 한국 사례. 5~6분 청중 질문. ‘본격 단계’ 메시지."),
            ("BRIDGE", "“Dify 봤다면 — 다중 모델 LibreChat과 문서 중심 AnythingLLM 빠르게.”"),
         ]),
    dict(no=8, lesson="1강", cat="LIBRECHAT·ANYTHINGLLM", lay="compare",
         headline="LibreChat · AnythingLLM — 특수 강점",
         sub="🟦 불변층 — 두 도구의 차별점",
         cards=[("LibreChat",
                 "다중 모델 동시 운영",
                 "ChatGPT·Claude·Gemini·Llama·Qwen 1 UI에서. ‘여러 모델 비교’ 강점. 가족·소그룹 자체 호스팅 인기. 사내 본격 — 단순. MIT 라이센스. GitHub 별 30,000+.",
                 "cyan"),
                ("AnythingLLM",
                 "문서 중심 · 부서 분리",
                 "‘부서별 워크스페이스’ — 영업·법무·HR 자연 분리. 문서 RAG 강점. 한국 법무·컨설팅 회사 일부 도입. MIT. GitHub 별 50,000+. Mintplex Labs 발.",
                 "purple")],
         bullets=[], time="5분 · LibreChat·AnythingLLM",
         notes=[
            ("SAY", "“UI 디테일 세 번째·네 번째 — LibreChat과 AnythingLLM. 특수 강점.”"),
            ("SAY", "“LibreChat — ‘다중 모델 동시 운영’. ChatGPT·Claude·Gemini·로컬 Llama·Qwen·Mistral을 1 UI에서. ‘여러 모델 비교’ 강점.”"),
            ("SAY", "“LibreChat 적합 — (1) ‘ChatGPT + Claude 동시 사용’ 회사. (2) ‘다양한 모델 비교’ R&D 팀. (3) ‘가족·소그룹 자체 호스팅’. 사내 50명+ 본격 운영은 단순.”"),
            ("SAY", "“AnythingLLM — ‘문서 중심·워크스페이스 분리’. ‘영업 워크스페이스 = 영업 문서만 학습’, ‘법무 워크스페이스 = 법무 문서만’. 자연스러운 부서 분리.”"),
            ("SAY", "“AnythingLLM 적합 — (1) ‘부서별 문서 분리’ 명확한 회사. (2) ‘법무·컨설팅·연구’ 같은 문서 중심 업무. (3) 직원 수 적은 부서 운영. 사용자 많은 본격 운영은 단순.”"),
            ("SAY", "“메시지 — Open WebUI가 ‘안전 표준’. LibreChat은 ‘다중 모델 특수’, AnythingLLM은 ‘부서별 문서 특수’. 둘 다 ‘우리 회사 특수 조건’ 맞을 때만 검토.”"),
            ("STORY", "LibreChat 공식. URL: librechat.ai, github.com/danny-avila/LibreChat. Danny Avila 2023 시작. MIT 라이센스. ChatGPT 클론으로 시작 → 다중 모델 통합 진화. 한국 자체 호스팅 사례 적음 (Open WebUI에 밀림). 가족·소그룹 자체 사용 인기."),
            ("STORY", "AnythingLLM 공식. Mintplex Labs 2023 시작. URL: useanything.com, github.com/Mintplex-Labs/anything-llm. MIT 라이센스. ‘문서 중심 챗봇’ 컨셉. 한국 — 법무·컨설팅·교육 회사 일부 도입."),
            ("STORY", "LibreChat 다중 모델 디테일 (강사 대응용). 1 UI에서 모델 선택 드롭다운. (1) OpenAI API → ChatGPT-4·4o·3.5. (2) Anthropic API → Claude 3.5. (3) Google API → Gemini. (4) 로컬 Ollama·vLLM. (5) Hugging Face. 각 모델 비교 + 응답 모음. 단 ‘여러 API 비용 합산’ — 비용 큼."),
            ("STORY", "AnythingLLM 워크스페이스 디테일 (강사 대응용). 워크스페이스 = ‘챗봇 + 문서 집합 + 권한’. 영업 워크스페이스 → 영업 직원만 접근 + 영업 문서만 검색 + 영업 챗 이력. 법무도 동일. ‘부서별 별도 챗봇’ 자연. 단 ‘부서 공통 챗봇’은 별도 추가."),
            ("NOTE", "★ 강사 핵심 배경지식 — 4종 중 ‘1순위 + 2순위’ 패턴: 1순위 — Open WebUI (한국 표준). 2순위 (조건부) — (1) Dify — 본격 워크플로우. (2) AnythingLLM — 부서별 문서. (3) LibreChat — 다중 모델 R&D. ‘1순위 시작 → 6개월 후 조건부 추가’."),
            ("NOTE", "강사 배경지식 — LibreChat 한국 사례 적은 이유: (1) Open WebUI가 ‘ChatGPT 비슷한 UI + 사내 본격’ 둘 다 충족. (2) ‘다중 모델 비교’ 필요성 일반 사내 적음. (3) 한국어 UI 완성도 약간 미흡. ‘소그룹·R&D’엔 의미, ‘본격 사내’ 부적합."),
            ("NOTE", "강사 배경지식 — AnythingLLM 한국 사례 적은 이유: (1) 부서별 권한 분리 — Open WebUI도 RBAC 가능. (2) 사용자 수 큰 운영 부담. (3) ‘부서별 분리’ 자체가 한국 회사 사내 챗봇 우선 요구 X. ‘문서 중심 특수 회사’만 의미."),
            ("Q", "예상 청중 질문 1: ‘LibreChat 좋아 보이는데?’ → 답: ‘‘여러 모델 비교’ 매력. 단 사내 본격 운영엔 ‘비용 + 운영’ 부담. 가족·소그룹 자체 호스팅 인기 이유.’"),
            ("Q", "예상 청중 질문 2: ‘우리는 부서별 분리 강한데 AnythingLLM?’ → 답: ‘검토 가치 있음. 단 ‘Open WebUI + RBAC + 워크스페이스(2025 신규)’도 동일 가능. 둘 다 비교 후 결정.’"),
            ("Q", "예상 청중 질문 3: ‘4종 다 자체 호스팅?’ → 답: ‘Open WebUI·LibreChat·AnythingLLM — 자체 호스팅 무료. Dify — 자체 호스팅 무료 + 클라우드 유료. 4종 다 자체 가능.’"),
            ("TIP", "강사 함정 — LibreChat·AnythingLLM 디테일 깊이 X: ‘위치만 알면 됨’ 메시지."),
            ("TIP", "강사 진행 팁 — 5분 시간 배분: 0~1분 두 도구 위치. 1~3분 LibreChat 디테일. 3~5분 AnythingLLM 디테일. ‘특수 조건만 검토’ 메시지."),
            ("BRIDGE", "“4종 다 봤다면 — 우리 회사 선택 매트릭스.”"),
         ]),
    dict(no=9, lesson="1강", cat="UI MATRIX", lay="bullets",
         headline="UI 선택 매트릭스",
         sub="🟦 불변층 — 4가지 조건 → 추천",
         bullets=[
            "★ 조건 1 — 사용자 수 (5명 / 50명 / 200명+)",
            "★ 조건 2 — 워크플로우 복잡도 (단순 챗 / 분기·통합)",
            "★ 조건 3 — 문서 우선도 (일반 챗 / 문서 중심)",
            "★ 조건 4 — 모델 다중 (1 모델 / 여러 모델)",
            "★ 추천 매트릭스 — 95% 한국 회사 → Open WebUI",
            "★ 특수 → Dify(통합) / AnythingLLM(문서) / LibreChat(다중)"],
         time="5분 · 선택 매트릭스",
         notes=[
            ("SAY", "“4종 봤다면 — 우리 회사 선택 매트릭스.”"),
            ("SAY", "“조건 1 사용자 수. 5명·50명·200명+. 200명+면 운영 강건한 도구 — Open WebUI·Dify.”"),
            ("SAY", "“조건 2 워크플로우 복잡도. 단순 챗 — Open WebUI. 분기·통합 — Dify.”"),
            ("SAY", "“조건 3 문서 우선도. 일반 챗 — 모든 도구 OK. 문서 중심 — AnythingLLM 또는 Open WebUI(워크스페이스).”"),
            ("SAY", "“조건 4 모델 다중. 1 모델(우리 자체) — Open WebUI. 여러 모델 비교 — LibreChat.”"),
            ("SAY", "“추천 매트릭스 — 95% 한국 회사 → Open WebUI. 특수 — Dify(본격 통합), AnythingLLM(부서별 문서), LibreChat(R&D 다중 모델).”"),
            ("SAY", "“단계적 접근 — 1단계(0~6개월) Open WebUI. 2단계(6~12개월) 부족 확인 시 추가 또는 갈아탐. ‘완벽 결정 X — 시작 → 운영 후 보완’.”"),
            ("STORY", "한국 회사 UI 도입 분포 (강사 대응용 추정). Open WebUI 약 60%. Dify 약 15%. AnythingLLM 약 10%. LibreChat 약 5%. 자체 개발 + 기타 약 10%. ‘Open WebUI 압도적 1위’."),
            ("STORY", "한국 회사 UI 도입 단계 (강사 대응용). 1단계(첫 도입) Open WebUI 시작. 2단계(6개월 후) 부족 확인 시 Dify·AnythingLLM 추가. 3단계(1~2년 후) 자체 개발 또는 Dify Enterprise. 약 90% 회사가 1단계에서 만족."),
            ("NOTE", "★ 강사 핵심 배경지식 — 매트릭스 적용 예시: (1) 50명 IT 회사 + 일반 챗 + Qwen 1개 모델 → Open WebUI. (2) 200명 핀테크 + 워크플로우 + 시스템 통합 → Dify. (3) 30명 법무 + 문서 중심 → AnythingLLM. (4) 20명 R&D + 다중 모델 비교 → LibreChat. (5) 100명 일반 회사 → Open WebUI."),
            ("NOTE", "강사 배경지식 — ‘2개 운영’ 패턴: 일반 사내는 Open WebUI(전 직원). 본격 워크플로우는 Dify(영업·CS 등 특수 부서). ‘1+1 분리 운영’ 한국 일부 회사 패턴. 단 운영 부담 1.5~2배."),
            ("NOTE", "강사 배경지식 — UI 자체 개발 옵션: 50%+ 한국 대기업이 ‘자체 개발’ 검토. ‘오픈소스 + 우리 디자인’ 조합. 비용 — 개발 1~3개월 + 유지보수 별도. 의미 — ‘브랜드·UX 절대’ 회사. 본 강좌 청중에게는 ‘처음 X, 6~12개월 후 검토’ 권장."),
            ("Q", "예상 청중 질문 1: ‘우리는 50명이지만 자체 개발 원함.’ → 답: ‘자체 개발 비용·시간 큼. 처음 6개월 Open WebUI 운영 → ‘직원이 진짜 원하는 디자인’ 파악 → 자체 개발 결정. 처음부터 자체 개발 = ‘안 쓰는 UI’ 위험.’"),
            ("Q", "예상 청중 질문 2: ‘부서별 분리 vs 통합 챗봇?’ → 답: ‘‘일반 챗 + 부서별 문서’ — Open WebUI + 워크스페이스. ‘부서별 완전 분리 + 다른 워크플로우’ — Dify 또는 AnythingLLM. 회사 문화에 따라.’"),
            ("Q", "예상 청중 질문 3: ‘UI 결정 후 갈아탐 어렵나?’ → 답: ‘UI는 비교적 쉬움. RAG 데이터·MCP 설정은 갈아탐 시 다시. 모델은 그대로 유지. 갈아탐 비용 — 1주 IT 작업.’"),
            ("TIP", "강사 함정 — ‘완벽 매트릭스’ X: ‘60% 답으로 시작’ 메시지."),
            ("TIP", "강사 진행 팁 — 5분 시간 배분: 0~1분 4가지 조건. 1~3분 매트릭스. 3~4분 단계적 접근. 4~5분 청중 질문."),
            ("BRIDGE", "“선택 매트릭스 봤다면 — UI 커스터마이징 (사내 브랜딩) 빠르게.”"),
         ]),
    dict(no=10, lesson="1강", cat="CUSTOMIZATION", lay="bullets",
         headline="UI 커스터마이징 — 사내 브랜딩",
         sub="🟦 불변층 — 기본 패턴",
         bullets=[
            "★ 로고·회사명·색상 — 5분 설정 (CSS 변수)",
            "★ 사내 도메인 + HTTPS — chat.회사.com 같은 주소 (2편 3강 Reverse Proxy)",
            "★ 사용자 로그인 — LDAP / SSO / OAuth 사내 통합",
            "★ 환영 메시지 + 사내 정책 안내 — ‘이 챗봇은 사내 전용...’",
            "★ 사용 가이드 통합 — ‘처음 사용 안내’ 화면",
            "★ ‘기본 UI’만 — 자체 개발 X. 6~12개월 후 자체 디자인 검토"],
         time="4분 · 커스터마이징",
         notes=[
            ("SAY", "“UI 결정했다면 — 사내 브랜딩 커스터마이징. 5분에 가능.”"),
            ("SAY", "“기본 설정 — 로고·회사명·색상. 관리자 페이지에서 5분에 완료. 직원이 ‘우리 회사 챗봇’ 느낌.”"),
            ("SAY", "“사내 도메인 — chat.회사.com 같은 주소. 2편 3강 Reverse Proxy(Nginx) + HTTPS 인증서로 구현. IT부 1일 작업.”"),
            ("SAY", "“사용자 로그인 — LDAP·SSO·OAuth 사내 통합. ‘회사 계정으로 자동 로그인’. Microsoft 365·Google Workspace 사용 회사는 OAuth 1시간 설정.”"),
            ("SAY", "“환영 메시지 — ‘이 챗봇은 사내 전용입니다. 외부 클라우드 전송 X. 회사 정책 ___ 준수.’ 같은 안내. 직원 안심.”"),
            ("SAY", "“사용 가이드 — ‘처음 사용 안내’ 화면 또는 사내 위키 링크. 직원 적응 도움.”"),
            ("SAY", "“원칙 — ‘기본 UI 충분’. 자체 디자인 개발 X. 6~12개월 후 ‘진짜 필요한 디자인’ 파악되면 검토.”"),
            ("STORY", "Open WebUI 커스터마이징 디테일. 관리자 페이지 → 인터페이스 → 로고·테마·환영 메시지. CSS 변수 직접 수정 가능. 약 10분 작업 + 디자이너 협업."),
            ("STORY", "사내 도메인 설정 (강사 대응용). chat.회사.com → Nginx Reverse Proxy → 사내 Open WebUI 서버. HTTPS = Let's Encrypt 무료 인증서. 2편 3강에서 다룸. IT부 1일 작업."),
            ("STORY", "직원 적응 사례 (강사 대응용). 한 한국 회사 — Open WebUI 도입 첫 주 사용률 30%. 환영 메시지 + 사내 정책 안내 추가 후 사용률 70% 상승. ‘우리 회사 도구’ 인식 중요. 정책 안내가 ‘직원 안심’ + ‘사용 동기’.”"),
            ("NOTE", "★ 강사 핵심 배경지식 — 커스터마이징 5가지 우선순위: (1) 로고·회사명 — 5분 (필수). (2) 사내 도메인 — 1일 (강력 권장). (3) SSO·LDAP — 1주 (50명+ 회사 권장). (4) 환영 메시지 + 정책 — 1시간 (필수). (5) 자체 디자인 — 1~3개월 (6~12개월 후 검토). 5가지가 도입 핵심."),
            ("NOTE", "강사 배경지식 — ‘브랜딩’이 사용률에 미치는 영향: ‘이 챗봇 우리 회사 거구나’ 느낌 → 사용률·신뢰 증가. 단순 로고·이름 변경만으로 사용률 약 20% 차이. 디자인 자체 개발은 ‘체감 차이 거의 X’ + ‘비용 큼’."),
            ("NOTE", "강사 배경지식 — Open WebUI 사내 정책 메시지 예시: ‘안내 — 이 챗봇은 사내 전용입니다. 외부 클라우드(ChatGPT 등) 전송 X. 모든 대화는 사내 서버에서만 처리·30일 보관. 민감 데이터(인사·M&A·고객 정보)는 입력 금지. 정책 준수.’ 약 200~300자. 환영 화면 + 첫 사용 안내."),
            ("Q", "예상 청중 질문 1: ‘자체 디자인 개발 정말 X?’ → 답: ‘‘기본 UI 충분’ 메시지. 6개월 운영 후 ‘진짜 필요’ 확인되면 검토. 처음부터 자체 = 안 쓰는 UI 위험.’"),
            ("Q", "예상 청중 질문 2: ‘사내 도메인 우리 IT 어떻게?’ → 답: ‘2편 3강 Nginx + HTTPS 가이드. 회사 도메인 DNS 추가(1시간) + Nginx 설정(2시간) + 인증서(1시간) = 1일.’"),
            ("Q", "예상 청중 질문 3: ‘브랜딩 디테일 어디까지?’ → 답: ‘로고·이름·환영 메시지만 필수. 색상·폰트는 ‘기본 그대로’ OK. 시간 1시간 안에.’"),
            ("TIP", "강사 함정 — ‘완벽 디자인 추구’ X: ‘5분 브랜딩 + 1일 도메인’ 권장. 자체 디자인은 시간 낭비."),
            ("TIP", "강사 진행 팁 — 4분 시간 배분: 0~1분 ‘5분 가능’. 1~2분 5가지 우선순위. 2~3분 정책 메시지 예시. 3~4분 ‘자체 개발 X’ 메시지."),
            ("BRIDGE", "“1강 마지막 — 실습. 우리 회사 UI 결정서.”"),
         ]),
    dict(no=11, lesson="1강", cat="WORKSHOP 1", lay="bullets",
         headline="실습 — 우리 회사 UI 결정서",
         sub="🟦 적용 (워크시트)",
         bullets=[
            "Q1 · 사용자 수 — 5명 / 50명 / 200명+?",
            "Q2 · 워크플로우 — 단순 챗 / 통합·분기?",
            "Q3 · 문서 vs 일반 — 문서 중심 / 일반 챗?",
            "Q4 · 1순위 UI = ___ (Open WebUI 90% 권장)",
            "Q5 · 사내 도메인 = chat.___.com",
            "★ 다음 액션 — IT부 1주 안 설치 + 챔피언 5명 사용"],
         time="8분 · 실습",
         notes=[
            ("SAY", "“1강 마지막 — 실습. UI 결정서 5칸.”"),
            ("DO", "조별 실습 (5분, 3~4인 1조). Q1~Q5 + 다음 액션."),
            ("SAY", "“권장 매트릭스. 95% 한국 회사 → Open WebUI. ‘사내 도메인 + 브랜딩 + LDAP·SSO’ 5칸 채우기.”"),
            ("Q", "발표 요청: “1~2조 발표. 1순위 UI만.” → 보통 ‘Open WebUI’. → ‘좋습니다. 정답.’"),
            ("NOTE", "★ 강사 핵심 배경지식 — 결정서 5칸 작성 가이드: (1) Q1 — 사용자 수에 따라 운영 부담. (2) Q2 — 일반 사내는 ‘단순 챗’. (3) Q3 — 문서 회사만 ‘문서 중심’. (4) Q4 — 95% Open WebUI. (5) Q5 — 회사 도메인 결정."),
            ("NOTE", "강사 배경지식 — 다음 주 액션 3가지: (1) 결정서 IT부 전달. (2) Open WebUI 1주 안 설치 (Docker 1줄). (3) 챔피언 5명 사용 시작 + 만족도 평가. 셋 다 2주 안에."),
            ("Q", "예상 청중 질문 1: ‘설치 후 사용자 어떻게 등록?’ → 답: ‘Open WebUI 관리자 페이지 — 사용자 추가 + 권한 부여. 또는 LDAP·OAuth 자동.’"),
            ("Q", "예상 청중 질문 2: ‘챔피언 5명 어떻게 선정?’ → 답: ‘1편 ‘챔피언 네트워크’ — 부서장 + 자원자 5명. ChatGPT 사용 경험 있는 사람 우선.’"),
            ("TIP", "강사 함정 — ‘완벽 결정 압박’ X: ‘1주 시작 → 운영 후 보완’."),
            ("TIP", "강사 진행 팁 — 8분 시간 배분: 0~5분 개별. 5~7분 발표. 7~8분 다음 액션."),
            ("BRIDGE", "“1강 끝. 잠깐 쉬고 2강 ‘RAG’로. 사내 문서 학습.”"),
         ]),
    dict(no=12, lesson="1강", cat="WRAP", lay="bullets",
         headline="1강 정리 — 4종 UI 중 Open WebUI",
         sub="🟦 마무리",
         bullets=[
            "① Open WebUI — 한국 자체 호스팅 표준 (95% 권장)",
            "② Dify — 본격 워크플로우 (6~12개월 후 검토)",
            "③ LibreChat — R&D 다중 모델 (소그룹)",
            "④ AnythingLLM — 부서별 문서 (특수 회사)",
            "★ 추천 시작 — Open WebUI + Qwen 7B + Ollama (3편 셋과 결합)",
            "★ 다음 — 2강 RAG (사내 문서 학습)"],
         time="3분 · 정리",
         notes=[
            ("SAY", "“1강 정리. 4종 UI. Open WebUI가 ‘95% 표준’. 6개월 운영 후 부족 확인되면 Dify·AnythingLLM·LibreChat 검토.”"),
            ("SAY", "“1강 핵심 메시지 — ‘기본 UI 충분, 시작 빨리, 운영 후 보완’.”"),
            ("SAY", "“2강 예고 — RAG. ‘사내 문서 학습’. 챗봇이 ‘일반 지식’만 답하면 ‘우리 회사 문서’ 학습이 필요. 2강이 그 방법.”"),
            ("NOTE", "★ 강사 핵심 배경지식 — 1강 끝 메시지: ‘UI는 결정 빠르게 + 시작 빠르게’ 격려. 너무 많은 시간 X."),
            ("TIP", "강사 진행 팁 — 3분 안에. 정리는 메시지 강조."),
            ("BRIDGE", "“쉬는 시간 10분. 2강에서.”"),
         ]),
    # ============================ 2강 ============================
    dict(no=13, lesson="2강", cat="INTRO · TITLE", lay="title",
         headline="RAG — 사내 문서 학습",
         sub="2강 — ‘우리 회사 문서 검색하는 AI’",
         bullets=[], time="3분 · 시작",
         notes=[
            ("SAY", "“2강입니다. ‘RAG’. ‘우리 회사 문서 검색하는 AI’ 만드는 기술.”"),
            ("SAY", "“2강 60분 동안 다섯 가지 — (1) RAG가 뭐고 왜, (2) RAG 4단계, (3) 벡터 DB·임베딩 도구, (4) ★ RAG 4계층 (Anthropic 사례), (5) PII Footer + 한국 사례. 결과 — ‘우리 회사 RAG 설계서 1페이지’.”"),
            ("SAY", "“2강 약속 — ‘초보자 톤’ 유지. ‘LlamaIndex 코드 직접 작성’ X. ‘우리 회사 RAG 결정 가능’ 수준.”"),
            ("Q", "도입 질문 1: “‘RAG’ 들어본 분?” → 보통 1/3. → ‘좋아요. RAG = Retrieval Augmented Generation. ‘검색 보강 생성’. 풀이는 본문에.’"),
            ("Q", "도입 질문 2: “사내 챗봇에 ‘우리 회사 문서’ 물어본 적 있는 분?” → 보통 다수. → ‘일반 LLM은 ‘몰라요’ 답. RAG가 그걸 ‘우리 회사 답’으로 바꿉니다.’"),
            ("NOTE", "★ 강사 핵심 배경지식 — 2강의 중요성: 사내 챗봇이 ‘일반 ChatGPT’와 같은 답이면 의미 작음. RAG가 ‘우리 회사 챗봇’으로 만드는 핵심. 1·2·3편이 ‘기술 결정’이었다면 RAG는 ‘진짜 가치 창출’ 단계."),
            ("NOTE", "강사 배경지식 — Anthropic Self-Service Data Analytics 인용: 본 강좌 2강 ‘RAG 4계층’은 Anthropic 공식 사례 직접 인용. URL: claude.com/blog/how-anthropic-enables-self-service-data-analytics-with-claude. Anthropic 사내 직원 44,000명 데이터 분석 RAG. 한국 회사 적용 가능 패턴."),
            ("NOTE", "강사 배경지식 — 2강 60분 시간 배분: 0~3분 인트로. 3~6분 학습목표. 6~14분 RAG가 뭐고 왜. 14~22분 RAG 4단계. 22~30분 벡터 DB·임베딩. 30~40분 ★ Anthropic 4계층 사례. 40~48분 PII Footer + 한국 사례. 48~54분 실습. 54~58분 마무리."),
            ("TIP", "강사 함정 — RAG 기술 자랑 X: ‘우리 회사가 RAG 도입 가능한지’ 중심. 청중에게 ‘쉽지 않지만 가능’ 안심."),
            ("BRIDGE", "“학습 목표 빠르게.”"),
         ]),
    dict(no=14, lesson="2강", cat="OBJECTIVES", lay="bullets",
         headline="60분 후, 이 3가지를 한다",
         sub="",
         bullets=[
            "① RAG 4단계(수집·청크·임베딩·검색) 설명한다",
            "② 한국 회사 RAG 도입 ‘작게 시작’ 패턴을 안다",
            "③ ‘우리 회사 RAG 설계서 1페이지’ 완성"],
         time="3분 · 학습목표",
         notes=[
            ("SAY", "“60분 후 셋. RAG 4단계, 작게 시작 패턴, 설계서 1페이지.”"),
            ("SAY", "“2강 핵심 메시지 — ‘RAG는 ‘처음부터 완벽’ X. ‘작게 시작 → 6개월 후 확장’ 정석. 한 부서·100문서로 시작 가능.”"),
            ("NOTE", "★ 강사 핵심 배경지식 — 2강 성공 기준: 청중이 ‘우리 IT부에 RAG 요구 시 어떻게 토론할지’. ‘직접 구현’이 아니라 ‘설계 가능’."),
            ("NOTE", "강사 배경지식 — RAG vs 파인튜닝: 3편 2강에서 ‘파인튜닝’ 봤음. RAG vs 파인튜닝 — RAG가 더 단순 + 새 정보 즉시 반영. 파인튜닝은 ‘회사 톤 학습’. 보통 ‘RAG 먼저, 6개월 후 파인튜닝 검토’ 순서."),
            ("TIP", "강사 진행 팁 — 학습 목표 3분 안에."),
            ("BRIDGE", "“본문 시작 — RAG가 뭐고 왜 필요한가.”"),
         ]),
    dict(no=15, lesson="2강", cat="WHY RAG", lay="compare",
         headline="RAG — Retrieval Augmented Generation",
         sub="🟦 불변층 — ‘회사 문서 + AI’ 결합",
         cards=[("RAG 없이",
                 "일반 LLM 답",
                 "‘우리 회사 출장비 규정?’ → ‘모릅니다 / 일반 규정...’. 사내 정보 X. ChatGPT와 같은 답. 의미 작음.",
                 "cyan"),
                ("RAG 사용",
                 "회사 문서 검색 + 답",
                 "‘출장비 규정?’ → 사내 정책 문서 검색 → ‘우리 회사 출장비 규정 제5조에 따르면...’. 정확·최신 사내 답.",
                 "purple")],
         bullets=[], time="6분 · 왜 RAG",
         notes=[
            ("SAY", "“RAG 풀이. ‘Retrieval Augmented Generation’ = ‘검색 보강 생성’. ‘검색 + 답 생성’ 조합 방식.”"),
            ("SAY", "“원리 — (1) 질문 받음. (2) ‘사내 문서’에서 관련 부분 검색. (3) 검색 결과를 LLM에 ‘참고 자료’로 제공. (4) LLM이 ‘참고 자료 기반’ 답 생성. 결과 — ‘우리 회사 정보 정확 답’.”"),
            ("SAY", "“RAG 없이 — 일반 LLM 답. ‘출장비 규정?’ → ‘모릅니다 / 일반 규정...’. ChatGPT와 같은 답.”"),
            ("SAY", "“RAG 사용 — 회사 문서 검색 → 정확·최신 사내 답. ‘우리 회사 출장비 규정 제5조에 따르면...’ 같은 답.”"),
            ("SAY", "“원칙 — 사내 챗봇의 진짜 가치는 RAG에서. ‘일반 챗봇’은 ChatGPT면 충분. ‘사내 챗봇 + RAG’만 의미.”"),
            ("STORY", "RAG 개념 출처. Facebook AI Research 2020 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks'. URL: arxiv.org/abs/2005.11401. ‘LLM + 외부 지식 검색’ 첫 본격 논문. 2023~2024 사내 도입 폭증."),
            ("STORY", "사내 RAG 도입 흔한 시나리오 (강사 대응용). (1) 사내 정책·규정 검색. (2) 사내 매뉴얼·SOP. (3) 영업 가이드·고객 정보. (4) 법무 계약서·판례. (5) HR 인사 정책. (6) 회사 위키·문서. ‘우리 회사 정보를 챗봇이 알기’의 모든 경우."),
            ("STORY", "한국 회사 RAG 도입 사례 (강사 대응용). 카카오·네이버 사내 위키 RAG. 일부 컨설팅 회사 ‘프로젝트 문서’ RAG. 법무법인 ‘판례 검색’ RAG. 중견 IT — ‘사내 정책 챗봇’ RAG. 2024년 본격, 2026년 표준."),
            ("NOTE", "★ 강사 핵심 배경지식 — RAG의 ‘5대 장점’: (1) 사내 정확 답. (2) 새 문서 즉시 반영 (파인튜닝 대비). (3) 모델 학습 X — 비용 적음. (4) 출처 명시 — ‘이 답은 ___ 문서에서’. (5) 회사 비밀 보호 — 사내 검색만, 모델 학습 X."),
            ("NOTE", "강사 배경지식 — RAG 3대 단점: (1) ‘검색이 정확해야 답이 정확’ — 검색 품질 결정. (2) 문서가 ‘이미지·표·복잡 구조’면 처리 어려움. (3) ‘비슷한 문서 많음’ 시 검색 혼란. 본 강좌 2강 후반에서 대응."),
            ("NOTE", "강사 배경지식 — RAG ‘검색’의 본질: 키워드 검색 X — ‘의미 검색’. ‘출장비’ 키워드 없이 ‘여행 보조금’ 검색해도 ‘출장비 규정’ 발견. 임베딩 + 벡터 검색 기술 (다음 슬라이드)."),
            ("NOTE", "강사 배경지식 — RAG ‘출처 명시’의 의미: LLM 답에 ‘출처 문서명 + 페이지’ 자동 표시. 직원이 ‘답 정확성’ 검증 가능. ‘이 답은 출처 ___, 페이지 5에서 추출’ 같은. 사내 챗봇 신뢰 핵심."),
            ("Q", "예상 청중 질문 1: ‘우리 사내 문서 다 학습 가능?’ → 답: ‘텍스트 문서 99% 가능. 이미지·표·복잡 PDF는 일부 어려움. ‘80% 정확’ 목표.’"),
            ("Q", "예상 청중 질문 2: ‘RAG vs 파인튜닝 결정?’ → 답: ‘RAG 먼저. ‘작게 시작 + 새 문서 즉시 반영’. 파인튜닝은 ‘회사 톤 절대 필요’ 시 추가.’"),
            ("Q", "예상 청중 질문 3: ‘민감 문서도 RAG 가능?’ → 답: ‘가능. 단 권한 분리 필수. ‘HR 문서는 HR만 검색’ 같은 RBAC. 본 강좌 9편(보안) 자세히.’"),
            ("TIP", "강사 함정 — ‘RAG 만능’ X: ‘검색 품질 + 문서 품질이 결정’. 노력 필요."),
            ("TIP", "강사 진행 팁 — 6분 시간 배분: 0~1분 ‘RAG 풀이’. 1~2분 원리 4단계. 2~3분 ‘5대 장점’. 3~4분 ‘3대 단점’. 4~5분 한국 사례. 5~6분 청중 질문."),
            ("BRIDGE", "“RAG가 뭐고 왜 봤다면 — 실제 4단계 디테일.”"),
         ]),
    dict(no=16, lesson="2강", cat="RAG 4 STEPS", lay="stats",
         headline="RAG 4단계 — 수집·청크·임베딩·검색",
         sub="🟦 불변층 — 표준 파이프라인",
         stats=[("1. 수집",
                 "사내 문서 가져오기",
                 "PDF·DOCX·HTML·웹·DB·메일 등 다양 소스. 자동 동기화 (1일 1회 등). 핵심 — 권한 확인 (HR 문서는 HR 사용자만)."),
                ("2. 청크",
                 "문서를 조각으로",
                 "큰 문서 → 작은 조각 (500~2,000자). ‘청크 크기’가 검색 품질 결정. 작으면 정확도 ↓, 크면 검색 시 정보 과다."),
                ("3. 임베딩",
                 "텍스트 → 숫자 벡터",
                 "‘출장비 규정’ → [0.23, 0.81, -0.45, ...] 1,024차원 벡터. ‘의미 위치’ 표현. 비슷한 의미 = 비슷한 벡터."),
                ("4. 검색·답",
                 "질문 → 벡터 → 검색 → 답",
                 "질문도 벡터화 → ‘비슷한 벡터의 문서’ 검색 (상위 5개) → LLM에 ‘참고 자료’로 → 답 생성. 1~2초 안.")],
         bullets=[], time="6분 · 4단계",
         notes=[
            ("SAY", "“RAG 4단계 — 수집·청크·임베딩·검색. 모든 RAG의 표준 흐름.”"),
            ("SAY", "“1단계 수집. 사내 문서 가져오기. PDF·DOCX·HTML·웹·DB·메일 등 다양. 자동 동기화 1일 1회 등.”"),
            ("SAY", "“2단계 청크. 큰 문서 → 작은 조각. 보통 500~2,000자. ‘청크 크기’가 검색 품질 결정. 작으면 정확도 ↓ (문맥 부족), 크면 검색 시 정보 과다.”"),
            ("SAY", "“3단계 임베딩. 텍스트 → 숫자 벡터. ‘출장비 규정’ → [0.23, 0.81, -0.45, ...] 1,024차원 벡터. ‘의미 위치’ 표현.”"),
            ("SAY", "“4단계 검색·답. 질문도 벡터화 → ‘비슷한 벡터의 문서’ 상위 5개 검색 → LLM에 ‘참고 자료’로 → 답 생성. 전체 1~2초.”"),
            ("STORY", "임베딩 풀이 (강사 대응용). ‘텍스트의 의미를 숫자 위치로’. 같은 의미 텍스트 = 가까운 위치, 다른 의미 = 먼 위치. 1,024차원 = 1,024개 숫자. ‘출장비’ ≈ ‘여행 보조금’ (가까움), ‘출장비’ ≈ ‘회의실 예약’ (멀음). 검색 = ‘질문 위치에 가까운 문서’ 찾기."),
            ("STORY", "청크 크기 best practice (강사 대응용). 일반 문서 — 500~1,000자. 매뉴얼·기술 문서 — 1,000~2,000자. 짧은 FAQ — 200~500자. 청크 ‘오버랩’ 50~200자 (문맥 보존). 본 강좌 6편 자세히."),
            ("STORY", "벡터 검색 속도 (강사 대응용). 일반 사내 RAG 문서 1만~100만 청크. 검색 100~500ms. ‘ANN (Approximate Nearest Neighbor)’ 알고리즘 (HNSW 등). Qdrant·ChromaDB 같은 벡터 DB 자동."),
            ("NOTE", "★ 강사 핵심 배경지식 — RAG 4단계의 ‘품질 결정’: (1) 수집 — 문서 빠짐 X. (2) 청크 — 크기·오버랩 균형. (3) 임베딩 — 모델 품질 (한국어 최적화 필요). (4) 검색 — 상위 N개·재정렬. 4단계 모두 중요. ‘청크 또는 임베딩 실패’ 시 검색 품질 ↓."),
            ("NOTE", "강사 배경지식 — ‘청크’의 함정: 청크가 ‘문서 의미 단위 분리’가 아니면 ‘반쪽 정보’. 예 — 정책 제5조 중간에서 청크 분리 → 절반 빠진 답. ‘마크다운 헤더 단위 분리’ 같은 의미 분리 권장. 본 강좌 6편 자세히."),
            ("NOTE", "강사 배경지식 — 임베딩 모델의 ‘한국어 최적화’ 중요성: 영어 학습 임베딩 모델은 ‘한국어 의미 위치’ 부정확. 한국어 임베딩 모델 — BGE-M3, E5-mistral, 또는 한국어 특화 (KoSimCSE 등). 5강 17번에서 자세히."),
            ("NOTE", "강사 배경지식 — RAG의 ‘비용·시간’: 첫 인덱싱 — 1만 문서 = 약 1시간 (임베딩 API 호출). 검색 — 1초 안. 비용 — 임베딩 API 1만 문서 약 $1~10. 자체 호스팅 임베딩 모델은 비용 0."),
            ("Q", "예상 청중 질문 1: ‘우리 PDF 표·이미지 많음. RAG OK?’ → 답: ‘80% OK. 표는 ‘마크다운 변환’ 도구로. 이미지는 ‘OCR + 텍스트화’. 또는 비전(이미지) LLM. 본 강좌 6편 자세히.’"),
            ("Q", "예상 청중 질문 2: ‘청크 크기 어떻게 결정?’ → 답: ‘일반 1,000자 시작. 검색 품질 테스트 후 조정. ‘답 정확도 70% 미만’ 시 청크 크기 조정.’"),
            ("Q", "예상 청중 질문 3: ‘RAG 직접 구현 vs 도구?’ → 답: ‘도구 권장. LlamaIndex·LangChain·Open WebUI 내장 RAG. 도구 사용 시 1주 시작. 직접 구현은 1~3개월.’"),
            ("TIP", "강사 함정 — 4단계 디테일 깊이 X: ‘구조 이해’만. 디테일은 IT부."),
            ("TIP", "강사 진행 팁 — 6분 시간 배분: 0~1분 4단계 흐름. 1~4분 각 1분씩. 4~5분 ‘품질 결정 포인트’. 5~6분 청중 질문. 비유 적극."),
            ("BRIDGE", "“4단계 봤다면 — 도구. 벡터 DB·임베딩·RAG 도구.”"),
         ]),
    dict(no=17, lesson="2강", cat="RAG TOOLS", lay="compare",
         headline="RAG 도구 — 벡터 DB · 임베딩 · 파이프라인",
         sub="🟦 불변층 — 도구 3계층",
         cards=[("벡터 DB",
                 "Qdrant · Chroma · Milvus · Weaviate",
                 "Qdrant — 한국 자체 호스팅 1위, Rust, 빠름. Chroma — 가장 단순, Python, 시작 권장. Milvus — 대규모, 엔터프라이즈. Weaviate — 그래프 통합.",
                 "cyan"),
                ("임베딩 모델",
                 "BGE-M3 · E5 · KoSimCSE",
                 "BGE-M3 — 한국어 강함, Hugging Face 1위. E5-mistral — 다국어 균형. KoSimCSE·KURE — 한국어 특화. 자체 호스팅 무료. Ollama 지원.",
                 "purple"),
                ("RAG 파이프라인",
                 "LlamaIndex · LangChain · Open WebUI",
                 "LlamaIndex — RAG 전용 1위, Python. LangChain — 범용 LLM 도구. Open WebUI — 내장 RAG (시작 1줄). Dify — 노코드. 시작 — Open WebUI 내장.",
                 "cyan")],
         bullets=[], time="6분 · RAG 도구",
         notes=[
            ("SAY", "“RAG 도구 3계층. 벡터 DB·임베딩 모델·RAG 파이프라인.”"),
            ("SAY", "“1계층 벡터 DB. Qdrant·Chroma·Milvus·Weaviate. Qdrant — 한국 1위, Rust로 빠름. Chroma — 가장 단순, 시작 권장. Milvus — 대규모. Weaviate — 그래프 통합.”"),
            ("SAY", "“2계층 임베딩 모델. BGE-M3 — 한국어 강함 1위. E5-mistral — 다국어. KoSimCSE·KURE — 한국어 특화. 자체 호스팅 무료. Ollama 지원.”"),
            ("SAY", "“3계층 RAG 파이프라인. LlamaIndex — RAG 전용 1위. LangChain — 범용. Open WebUI — 내장 (시작 1줄). Dify — 노코드.”"),
            ("SAY", "“추천 시작 — Open WebUI 내장 RAG. 1줄로 시작. 6개월 운영 후 ‘부족’ 확인되면 LlamaIndex 자체 구현 검토.”"),
            ("STORY", "Qdrant 공식. URL: qdrant.tech, github.com/qdrant/qdrant. Rust 작성, Apache 2.0. ‘속도·정확도 균형 1위’. 한국 자체 호스팅 60%+. Docker 1줄 설치."),
            ("STORY", "Chroma 공식. URL: trychroma.com, github.com/chroma-core/chroma. Python, Apache 2.0. ‘가장 단순한 벡터 DB’. 시작 진입 장벽 최소. 한국 약 20%."),
            ("STORY", "BGE-M3 출처. BAAI(중국 베이징 AI연구원) 2024. URL: huggingface.co/BAAI/bge-m3. ‘다국어 + 한국어 강함 + 1,024차원 + 8K 문맥’. 한국 RAG 임베딩 1위. 무료, Apache 2.0."),
            ("STORY", "LlamaIndex 출처. URL: llamaindex.ai, github.com/run-llama/llama_index. Jerry Liu 창업. ‘RAG 전용 1위’. MIT 라이센스. Python. 본 강좌 4편 사용 가이드. 단 ‘코딩 필요’ — 1~2주 학습."),
            ("STORY", "LangChain 출처. URL: langchain.com, github.com/langchain-ai/langchain. Harrison Chase 창업. ‘범용 LLM 도구’ — RAG·에이전트·메모리·체인. Python·JS. 매우 인기 + 학습 부담 큼. 본 강좌 6편 자세히."),
            ("NOTE", "★ 강사 핵심 배경지식 — 추천 시작 ‘Open WebUI 내장 RAG’: Open WebUI 설정에서 ‘RAG 활성’ + 임베딩 모델(BGE-M3 자동) + 벡터 DB(자체 ChromaDB) → 문서 업로드 → 즉시 RAG. 1줄 시작. 단 ‘대규모 문서·세밀 제어’ 부족 → LlamaIndex 직접 구현 검토."),
            ("NOTE", "강사 배경지식 — 벡터 DB 4가지 디테일 비교: Qdrant — 빠름·정확. Chroma — 단순·작은 규모. Milvus — 큰 규모·엔터프라이즈. Weaviate — 그래프 검색. 일반 사내 RAG — Qdrant 또는 Chroma."),
            ("NOTE", "강사 배경지식 — 임베딩 모델 4가지 디테일: BGE-M3 — 다국어·한국어 1위. E5-mistral — 다국어 균형. nomic-embed-text — 영어 1위. ko-sroberta-multitask·KURE — 한국어 특화. 한국 추천 — BGE-M3."),
            ("NOTE", "강사 배경지식 — RAG 파이프라인 학습 곡선: (1) Open WebUI 내장 — 1줄, 1일. (2) LlamaIndex — 1~2주 학습, 코딩. (3) LangChain — 2~4주, 코딩. (4) Dify 노코드 — 1주 학습, UI. 학습 비용 vs 제어 트레이드오프."),
            ("NOTE", "강사 배경지식 — Hugging Face MTEB Korean 리더보드: 한국어 임베딩 모델 공식 벤치마크. URL: huggingface.co/spaces/upskyy/ko-mteb-leaderboard. BGE-M3·KURE·E5·KoSimCSE 점수 비교. 매월 업데이트."),
            ("Q", "예상 청중 질문 1: ‘우리 시작 — Open WebUI 내장 OK?’ → 답: ‘100% OK. 1줄 시작. 본격 단계 (10,000 문서+) 시 LlamaIndex 갈아탐 검토.’"),
            ("Q", "예상 청중 질문 2: ‘BGE-M3 자체 호스팅?’ → 답: ‘Ollama 지원. ‘ollama pull bge-m3’ 한 줄. 또는 Hugging Face 직접 다운로드. 자체 호스팅 무료.’"),
            ("Q", "예상 청중 질문 3: ‘RAG 파이프라인 직접 구현 필요한가?’ → 답: ‘시작은 X. Open WebUI 내장 충분. ‘세밀 제어·대규모’ 시 LlamaIndex.’"),
            ("TIP", "강사 함정 — 도구 비교 디테일 깊이 X: ‘시작 도구만’. 디테일은 6편(하네스)."),
            ("TIP", "강사 진행 팁 — 6분 시간 배분: 0~1분 3계층. 1~3분 각 1분씩. 3~4분 추천 시작. 4~5분 학습 곡선. 5~6분 청중 질문."),
            ("BRIDGE", "“도구 봤다면 — ★ 핵심. Anthropic 사례 ‘RAG 4계층 스택’.”"),
         ]),
    dict(no=18, lesson="2강", cat="ANTHROPIC 4 LAYERS", lay="stats",
         headline="★ RAG 4계층 (Anthropic 공식 사례)",
         sub="🟨 검증 사례 · Anthropic 44,000명 데이터 분석 RAG",
         stats=[("L1 데이터 카탈로그",
                 "‘어디에 무엇이’ 정리",
                 "사내 데이터 위치·소유자·민감도 메타데이터. ‘이 문서는 어느 부서, 누가 책임’ 사전. RAG의 ‘지도’."),
                ("L2 시맨틱 모델",
                 "‘의미 표준화’",
                 "용어 표준화 — ‘출장비’ = ‘여행비’ = ‘travel expense’. 부서별 다른 용어 통합. RAG ‘번역’ 역할."),
                ("L3 RAG 검색",
                 "벡터 + 키워드 결합",
                 "벡터 검색 (의미) + 키워드 검색 (정확) 결합. ‘하이브리드 검색’. 단독 벡터 또는 키워드보다 정확도 ↑."),
                ("L4 LLM + 응답",
                 "Claude·GPT 응답 + 출처",
                 "검색 결과를 LLM에 → 답 + 출처 명시. PII Footer (다음 슬라이드). 사용자 검증 가능.")],
         bullets=[], time="6분 · Anthropic 4계층",
         notes=[
            ("SAY", "“RAG 핵심 — Anthropic 사내 사례. 44,000명 직원 데이터 분석 RAG의 ‘4계층 스택’.”"),
            ("SAY", "“Anthropic은 ‘사내 직원 누구나 데이터 분석 가능’ 시스템 구축. 일반 RAG보다 더 정교. ‘L1 카탈로그 → L2 시맨틱 모델 → L3 검색 → L4 LLM’ 4계층.”"),
            ("SAY", "“L1 데이터 카탈로그. ‘어디에 무엇이 있는지’ 정리. 사내 데이터 위치·소유자·민감도 메타데이터. ‘이 문서는 어느 부서, 누가 책임’ 사전.”"),
            ("SAY", "“L2 시맨틱 모델. ‘의미 표준화’. 용어 표준 — ‘출장비’ = ‘여행비’ = ‘travel expense’. 부서별 다른 용어 통합. RAG ‘번역’ 역할.”"),
            ("SAY", "“L3 RAG 검색. 벡터 (의미) + 키워드 (정확) 결합. ‘하이브리드 검색’. 단독 벡터 또는 키워드보다 정확도 ↑.”"),
            ("SAY", "“L4 LLM + 응답. 검색 결과를 LLM에 → 답 + 출처 명시. PII Footer (개인정보 보호). 사용자 검증 가능.”"),
            ("SAY", "“한국 회사 적용 — 4계층 한 번에 X. L3·L4 먼저 (작은 RAG). L1 추가 (1년+). L2 추가 (2년+). 단계별. ‘Anthropic 수준’ 도달은 2~3년.”"),
            ("STORY", "Anthropic Self-Service Data Analytics 사례. 출처: Anthropic 공식 블로그 'How Anthropic enables self-service data analytics with Claude'. URL: claude.com/blog/how-anthropic-enables-self-service-data-analytics-with-claude. 사내 직원 44,000명 데이터 분석 시스템. 핵심 — ‘직원이 SQL 모름 + 데이터 위치 모름’ → 자연어 질문 → 자동 답."),
            ("STORY", "L1 데이터 카탈로그 (강사 대응용). ‘데이터의 데이터’ 메타데이터. (1) 위치 — DB·파일·테이블. (2) 소유자 — 책임 부서·담당자. (3) 민감도 — 공개·내부·민감·극비. (4) 갱신 주기. (5) 관련 문서. 한국 도구 — Datahub, Apache Atlas, Amundsen (LinkedIn). 본 강좌 11편 자세히."),
            ("STORY", "L2 시맨틱 모델 (강사 대응용). 부서별 다른 용어를 표준 의미로. ‘영업 부서 ‘딜’ = HR ‘프로젝트’ = 재무 ‘건’’ 같은 통합. ‘비즈니스 용어 사전’. 한국 도구 — Cube, dbt, Lightdash. 본 강좌 11편 자세히."),
            ("STORY", "하이브리드 검색 (강사 대응용). 벡터 검색 — 의미 비슷한 문서 (예 — ‘출장비’와 ‘여행 보조금’). 키워드 검색 — 정확한 단어 (예 — ‘B-2025-001’ 같은 코드). 둘 결합 = 정확도 ↑. Qdrant·Elasticsearch 결합 또는 Qdrant 내장 하이브리드."),
            ("NOTE", "★ 강사 핵심 배경지식 — 4계층의 한국 회사 도입 단계: (1) 0~6개월 — L3+L4. ‘간단 RAG’ Open WebUI 내장. (2) 6~12개월 — L4에 PII Footer 추가. (3) 1~2년 — L1 카탈로그. (4) 2~3년 — L2 시맨틱 모델. ‘완전한 4계층’은 대기업·본격 운영."),
            ("NOTE", "강사 배경지식 — L1 카탈로그의 ‘실전 가치’: 직원이 ‘우리 회사 ___ 데이터 어디 있나’ 질문 자주. L1 없으면 매번 IT부 문의. L1 있으면 챗봇이 ‘___는 영업 DB 매출 테이블’ 답 가능. 직원 효율 + IT 부담 ↓."),
            ("NOTE", "강사 배경지식 — L2 시맨틱 모델의 ‘부서 통합’: 한 한국 회사 — 영업 ‘딜’, 마케팅 ‘프로젝트’, CS ‘케이스’. 같은 ‘고객 거래’ 다른 용어. L2 없으면 ‘영업 딜 수’ 질문 X 다른 부서 이해. L2 있으면 ‘우리 회사 = 거래’ 표준."),
            ("NOTE", "강사 배경지식 — Anthropic 사례의 한국 시사점: Anthropic 44,000명 = 한국 대기업 규모. 단 ‘처음부터 4계층’ X — Anthropic도 단계별 구축. 한국 대기업 — 4계층 본격 검토. 중견 — L3+L4 시작. 중소 — L4만 (간단 RAG)."),
            ("Q", "예상 청중 질문 1: ‘우리 회사 어느 단계 시작?’ → 답: ‘작은 회사 (50명 이하) — L3+L4 시작. 중견 (50~500명) — L3+L4 + 단순 L1. 대기업 — 4계층 본격.’"),
            ("Q", "예상 청중 질문 2: ‘L1 카탈로그 직접 만들기?’ → 답: ‘‘부서별 책임 데이터 목록 1페이지’ 만드는 게 시작. 자동화 도구(Datahub 등)는 1년+. 1페이지 수동 작성도 가치 큼.’"),
            ("Q", "예상 청중 질문 3: ‘하이브리드 검색 도구?’ → 답: ‘Qdrant 내장 또는 Elasticsearch + Qdrant 결합. 본 강좌 6편 자세히. 시작은 Open WebUI 내장 (벡터만).’"),
            ("TIP", "강사 함정 — 4계층 ‘완벽 도입’ 압박 X: ‘L3+L4 시작 → 단계별 확장’. 처음부터 4계층 = 비용 큼."),
            ("TIP", "강사 진행 팁 — 6분 시간 배분: 0~1분 ‘Anthropic 사내 사례’. 1~4분 4계층 디테일. 4~5분 한국 도입 단계. 5~6분 청중 질문. ‘단계별 도입’ 메시지."),
            ("BRIDGE", "“4계층 봤다면 — 한국 사례 + PII Footer (개인정보 보호).”"),
         ]),
    dict(no=19, lesson="2강", cat="PII FOOTER", lay="bullets",
         headline="PII Footer + 한국 사례",
         sub="🟦 불변층 — 개인정보 보호 패턴",
         bullets=[
            "★ PII = Personally Identifiable Information (개인 식별 정보)",
            "★ Anthropic ‘PII Footer’ — RAG 답에 ‘이 답에 PII 포함’ 자동 표시",
            "★ 예 — ‘답에 직원 5명 이름·이메일 포함됨. 외부 공유 시 주의.’",
            "★ 한국 적용 — 개인정보보호법 + 사내 정책 결합",
            "★ 한국 사례 — 사내 챗봇이 인사·고객·M&A 정보 노출 사고 방지",
            "★ 구현 — RAG 응답에 ‘PII 감지 + 푸터 추가’ 자동화 (LLM 도움)"],
         time="5분 · PII Footer",
         notes=[
            ("SAY", "“RAG의 핵심 보안 — PII Footer. Anthropic 사례 직접 인용.”"),
            ("SAY", "“PII = Personally Identifiable Information = 개인 식별 정보. 이름·이메일·전화·주민번호 등 ‘개인 식별 가능 정보’.”"),
            ("SAY", "“Anthropic ‘PII Footer’ — RAG 답에 ‘이 답에 PII 포함됨’ 자동 표시. 예 — ‘답에 직원 5명 이름·이메일 포함. 외부 공유 시 주의.’”"),
            ("SAY", "“의미 — 사내 챗봇 답이 ‘개인정보 포함’임을 사용자가 즉시 인지. ‘외부 슬랙 공유’, ‘이메일 첨부’ 같은 부주의 방지.”"),
            ("SAY", "“한국 적용 — 개인정보보호법 + 사내 정책 결합. ‘직원 동의 받음 / 미受’, ‘이 정보 외부 공유 시 위반’ 같은 안내.”"),
            ("SAY", "“구현 — RAG 응답에 ‘PII 감지 + 푸터 추가’ 자동화. LLM에 ‘답에 PII 포함되면 푸터 추가’ 프롬프트. 또는 정규식·도구로 자동 감지.”"),
            ("STORY", "PII Footer 출처. Anthropic 'Self-Service Data Analytics' 사례 명시. ‘When PII appears in the response, we automatically add a footer’ 직접 인용. 한국 회사 적용 가치 큼."),
            ("STORY", "한국 PII 사고 사례 (강사 대응용). 2024년 한국 한 회사 — 사내 챗봇이 직원 인사 정보 답 → 직원이 ‘외부 슬랙에 공유’ → 개인정보 유출 사고. 사후 ‘PII 푸터 + 사내 정책 안내’ 추가. 본 강좌 9편(보안) 자세히."),
            ("STORY", "PII 종류 (강사 대응용). (1) 직접 PII — 이름·주민번호·이메일·전화. (2) 간접 PII — IP·생년월일·주소 (조합 시 식별). (3) 민감 PII — 건강·생체·신용·정치. 한국 개인정보보호법 차등 보호. RAG 답에 모두 감지 + 푸터 추가 권장."),
            ("NOTE", "★ 강사 핵심 배경지식 — PII Footer 구현 3가지 패턴: (1) LLM 프롬프트 — ‘답에 PII 포함 시 푸터 추가’ 시스템 프롬프트. 단순. 단 LLM 누락 가능. (2) 정규식·도구 — Microsoft Presidio·Google DLP. 정확 + 학습 부담. (3) 결합 — LLM + 도구. 본 강좌 9편 자세히."),
            ("NOTE", "강사 배경지식 — 한국 PII 자동 감지의 어려움: 한국 이름은 ‘3글자 한글’ 흔함 → 일반 단어와 구분 어려움. 영어 ‘John Smith’보다 어려움. 한국어 PII 도구 — KoNLPy + 정규식 결합. 본 강좌 6편 자세히."),
            ("NOTE", "강사 배경지식 — RAG ‘답 차단’ vs ‘푸터 추가’ 결정: (1) 차단 — 답 전체 X. 직원 불편. (2) 푸터 — 답 + 경고. 직원 인지. (3) 마스킹 — 답에 이름 ‘***’ 대체. 인사 정보엔 차단, 일반 정보엔 푸터 권장."),
            ("NOTE", "강사 배경지식 — 한국 개인정보보호법 + RAG: 개인정보처리 시 ‘이용 목적 명시’, ‘정보주체 동의’ 필요. 사내 챗봇은 ‘직원 동의 + 사내 사용’ 명시. RAG 답에 외부 송신 X. 본 강좌 9편 자세히."),
            ("Q", "예상 청중 질문 1: ‘우리 회사 PII Footer 구현?’ → 답: ‘처음은 LLM 시스템 프롬프트 — 1시간. 본격은 Microsoft Presidio 같은 도구 — 1주.’"),
            ("Q", "예상 청중 질문 2: ‘일반 답에 푸터 매번 안 보이게?’ → 답: ‘PII 감지 시만 푸터. 일반 답엔 X. 한국 도구 결합 권장.’"),
            ("Q", "예상 청중 질문 3: ‘챗봇 답 외부 공유 차단 가능?’ → 답: ‘기술적으로 어려움 (스크린샷·복사 가능). PII Footer + 사내 정책 + 직원 교육 결합. 본 강좌 9편 자세히.’"),
            ("TIP", "강사 함정 — PII 디테일 깊이 X: ‘푸터 추가 패턴’ 메시지만."),
            ("TIP", "강사 진행 팁 — 5분 시간 배분: 0~1분 ‘PII 풀이’. 1~2분 Anthropic 패턴. 2~3분 한국 사고 사례. 3~4분 구현. 4~5분 청중 질문."),
            ("BRIDGE", "“2강 마지막 — 실습. 우리 회사 RAG 설계서.”"),
         ]),
    dict(no=20, lesson="2강", cat="WORKSHOP 2", lay="bullets",
         headline="실습 — 우리 회사 RAG 설계서",
         sub="🟦 적용 (워크시트)",
         bullets=[
            "Q1 · 첫 RAG 대상 문서 — 어느 부서·몇 건?",
            "Q2 · 도구 — Open WebUI 내장 / LlamaIndex / Dify?",
            "Q3 · 임베딩 — BGE-M3 / KURE / 다른?",
            "Q4 · 4계층 시작 — L3+L4 (작은 RAG) / L1 추가 / L2 추가?",
            "Q5 · PII Footer 적용?",
            "★ 다음 액션 — IT부 + 챔피언 부서 협업, 2주 안 시작"],
         time="8분 · 실습",
         notes=[
            ("SAY", "“2강 실습 — RAG 설계서 5칸.”"),
            ("DO", "조별 실습 (5분, 3~4인 1조). Q1~Q5 + 다음 액션."),
            ("SAY", "“권장 시작 — 1부서 + 100건 문서 + Open WebUI 내장 + BGE-M3 + L3+L4 + 단순 PII 경고. ‘작게 시작’ 정석.”"),
            ("Q", "발표 요청: “1순위 부서 + 문서 수.” → 다양."),
            ("NOTE", "★ 강사 핵심 배경지식 — RAG 설계서 5칸 작성 가이드: (1) Q1 — ‘가장 자주 묻는 부서’ — 보통 HR·법무·정책 부서. 100~500건 시작. (2) Q2 — Open WebUI 내장. (3) Q3 — BGE-M3. (4) Q4 — L3+L4 시작. (5) Q5 — 단순 LLM 프롬프트 푸터부터."),
            ("NOTE", "강사 배경지식 — 다음 주 액션 3가지: (1) RAG 설계서 IT부 + 챔피언 부서 전달. (2) 1부서 100~500건 문서 모으기 (1주). (3) Open WebUI RAG 활성화 + 임베딩 (1일). 셋 다 2주 안에 시작."),
            ("Q", "예상 청중 질문 1: ‘100건 너무 적은가?’ → 답: ‘처음은 100건 적절. 검색 품질 테스트 + 평가 시작. ‘잘 작동 확인’ 후 1,000건·1만 건 확장.’"),
            ("Q", "예상 청중 질문 2: ‘부서별 다른 RAG 가능?’ → 답: ‘권장. HR 워크스페이스 → HR 문서만. AnythingLLM 또는 Open WebUI 워크스페이스. RBAC 권한 분리.’"),
            ("Q", "예상 청중 질문 3: ‘PII Footer 부족하면?’ → 답: ‘기본 LLM 프롬프트 시작. 부족 확인되면 Microsoft Presidio 같은 도구 추가. 6개월 단계.’"),
            ("TIP", "강사 함정 — ‘완벽 설계 압박’ X: ‘작게 시작’ 메시지."),
            ("TIP", "강사 진행 팁 — 8분 시간 배분: 0~5분 개별. 5~7분 발표. 7~8분 액션."),
            ("BRIDGE", "“2강 끝. 잠깐 쉬고 3강 ‘MCP’로. ERP·메일·DB 연결.”"),
         ]),
    dict(no=21, lesson="2강", cat="WRAP", lay="bullets",
         headline="2강 정리 — RAG 4단계 + 4계층",
         sub="🟦 마무리",
         bullets=[
            "RAG 4단계 — 수집·청크·임베딩·검색",
            "도구 — Open WebUI 내장 시작 (BGE-M3 임베딩)",
            "★ 4계층 (Anthropic) — L3+L4 시작 → L1·L2 단계 확장",
            "★ PII Footer — 개인정보 보호 + 사용자 인지",
            "★ 다음 — 3강 MCP (외부 시스템 연결)"],
         time="3분 · 정리",
         notes=[
            ("SAY", "“2강 정리. RAG 4단계 + Anthropic 4계층 + PII Footer. 시작 — Open WebUI 내장 + BGE-M3 + L3+L4.”"),
            ("SAY", "“2강 핵심 메시지 — ‘작게 시작 + 단계별 확장 + 개인정보 보호’.”"),
            ("SAY", "“3강 예고 — MCP. ‘우리 회사 ERP·메일·DB에서 정보 가져오기’. RAG가 ‘문서 검색’이라면 MCP는 ‘시스템 직접 연결’.”"),
            ("TIP", "강사 진행 팁 — 3분 안에."),
            ("BRIDGE", "“쉬는 시간 10분. 3강에서.”"),
         ]),
    # ============================ 3강 ============================
    dict(no=22, lesson="3강", cat="INTRO · TITLE", lay="title",
         headline="MCP — Model Context Protocol",
         sub="3강 — ERP · 메일 · CAD · 사내 시스템 연결",
         bullets=[], time="3분 · 시작",
         notes=[
            ("SAY", "“3강 ‘MCP — Model Context Protocol’입니다. 4편의 마지막. 1강 ‘UI’, 2강 ‘RAG’, 3강 ‘외부 시스템 연결’.”"),
            ("SAY", "“3강 60분 동안 다섯 — (1) MCP가 뭐고 왜, (2) MCP 아키텍처, (3) 공식 MCP 서버 + 한국 시스템 연결, (4) MCP 보안, (5) 한국 사례 + 실습. 결과 — ‘우리 회사 MCP 도입 결정서’.”"),
            ("SAY", "“3강 약속 — MCP는 2024년 11월 Anthropic이 출시한 신규 프로토콜. ‘초보자에게 어려움’ 가능성. 단순 풀이 + 비유로 진행. ‘우리 회사 MCP 도입 결정’ 가능 수준 목표.”"),
            ("Q", "도입 질문 1: “‘MCP’ 들어본 분?” → 보통 거의 없음. → ‘좋아요. 2024.11 신규. 6개월 안 ‘AI의 USB-C’ 평가 받는 중.’"),
            ("Q", "도입 질문 2: “사내 챗봇이 ‘오늘 매출 얼마?’ 답 가능?” → 보통 X. → ‘RAG는 ‘문서 검색’만. MCP가 ‘ERP 직접 연결 → 매출 데이터 가져오기’ 가능하게.’"),
            ("NOTE", "★ 강사 핵심 배경지식 — MCP의 중요성: ChatGPT 같은 일반 LLM은 ‘대화’만. RAG는 ‘문서 검색’. MCP는 ‘외부 시스템 직접 호출’. 진정한 ‘업무 도구’ 완성. 본 강좌 5편(에이전트)의 기반."),
            ("NOTE", "강사 배경지식 — MCP 출처: Anthropic 'Introducing the Model Context Protocol' 2024-11-25. URL: anthropic.com/news/model-context-protocol. ‘오픈 표준’ — 누구나 사용 가능. Microsoft·Google·OpenAI도 6개월 안 채택 추세."),
            ("NOTE", "강사 배경지식 — 3강 60분 시간 배분: 0~3분 인트로. 3~6분 학습목표. 6~14분 MCP가 뭐고 왜. 14~24분 MCP 아키텍처. 24~34분 공식 + 한국 시스템 연결. 34~44분 MCP 보안. 44~52분 한국 사례. 52~58분 실습. 58~60분 마무리."),
            ("TIP", "강사 함정 — MCP 기술 디테일 깊이 X: ‘아이디어 + 활용 가능성’ 메시지."),
            ("BRIDGE", "“학습 목표 빠르게.”"),
         ]),
    dict(no=23, lesson="3강", cat="OBJECTIVES", lay="bullets",
         headline="60분 후, 이 3가지를 한다",
         sub="",
         bullets=[
            "① MCP가 뭐고 왜 ‘AI의 USB-C’인지 설명한다",
            "② 우리 회사 ERP·메일·DB 중 MCP 연결 우선순위 결정한다",
            "③ ‘우리 회사 MCP 도입 결정서 1페이지’ 완성"],
         time="3분 · 학습목표",
         notes=[
            ("SAY", "“60분 후 셋. MCP 풀이 + USB-C 비유, 한국 시스템 우선순위, 결정서.”"),
            ("SAY", "“3강 핵심 메시지 — ‘MCP는 표준 + 안전 + 확장 가능. 단 초기 단계 — 작게 시작’.”"),
            ("NOTE", "★ 강사 핵심 배경지식 — 3강 성공 기준: 청중이 ‘우리 회사 MCP 시작 가치 있는지’ + ‘어디부터’ 판단 가능."),
            ("NOTE", "강사 배경지식 — MCP가 ‘AI의 USB-C’ 비유 의미: USB-C가 ‘모든 기기 단일 표준 연결’. MCP가 ‘모든 시스템 단일 표준 AI 연결’. 기존 — 각 시스템마다 별도 API. MCP — 통일 프로토콜."),
            ("TIP", "강사 진행 팁 — 학습 목표 3분 안에."),
            ("BRIDGE", "“본문 시작 — MCP가 뭔가.”"),
         ]),
    dict(no=24, lesson="3강", cat="WHY MCP", lay="compare",
         headline="MCP — Model Context Protocol",
         sub="🟦 불변층 — ‘AI의 USB-C’",
         cards=[("MCP 없이",
                 "시스템별 별도 통합",
                 "ERP·메일·CRM 각각 ‘우리 챗봇 → API 호출’ 별도 코드. 시스템 N개 = N개 통합. 비용 큼. 유지보수 부담.",
                 "cyan"),
                ("MCP 사용",
                 "표준 프로토콜 + 서버",
                 "각 시스템에 ‘MCP 서버’ 추가 → 챗봇이 표준 MCP 클라이언트로 연결. 시스템 추가 = MCP 서버만. 통일.",
                 "purple")],
         bullets=[], time="6분 · MCP 풀이",
         notes=[
            ("SAY", "“MCP 풀이. ‘Model Context Protocol’ = ‘AI 모델 외부 시스템 연결 표준 프로토콜’.”"),
            ("SAY", "“비유 — USB-C. 예전 — 충전 케이블 종류별 다름 (Micro-USB·Lightning·Type-A 등). USB-C — 모든 기기 단일 표준. 편함.”"),
            ("SAY", "“MCP도 동일. 기존 — 챗봇 → ERP API, 챗봇 → 메일 API, 챗봇 → DB API. 각각 다른 코드. MCP — 챗봇 → MCP 클라이언트 (표준) → MCP 서버 (각 시스템). 통일.”"),
            ("SAY", "“핵심 — 챗봇과 ‘외부 시스템’ 사이 ‘표준 다리’. 시스템 추가 = MCP 서버만 만들기. 챗봇 코드 변경 X.”"),
            ("SAY", "“오픈 표준 — 누구나 사용. Anthropic 출시 (2024.11) 후 — Microsoft Copilot, Google Workspace, OpenAI Plugin 호환 진화 중. 사실상 ‘업계 표준’.”"),
            ("STORY", "MCP 공식 출처. Anthropic 'Introducing the Model Context Protocol' 2024-11-25. URL: anthropic.com/news/model-context-protocol. ‘오픈 표준 + 오픈소스 SDK + 공식 서버 목록’. 6개월 안 폭발적 채택."),
            ("STORY", "MCP의 ‘AI USB-C’ 표현 출처. Anthropic 공식 + 다수 매체 (TechCrunch·VentureBeat 2024.11~12) 비유. ‘the USB-C of AI integrations’. 직관적 + 빠른 이해."),
            ("STORY", "MCP 등장 배경 (강사 대응용). 2023~2024 ChatGPT Plugin·OpenAI Function Calling 등 ‘LLM + 외부 시스템’ 시도 다수. 단 ‘업체별 다른 표준’ → 호환 X. Anthropic이 ‘오픈 표준’ 제안 → 빠른 채택."),
            ("STORY", "Microsoft·Google·OpenAI 채택 (강사 대응용). 2025년 들어 Microsoft Copilot Studio, Google Workspace, OpenAI도 MCP 지원 발표. ‘업계 표준’ 위치 확정. 한국 회사도 ‘MCP 지원 도구 채택’ 안전."),
            ("NOTE", "★ 강사 핵심 배경지식 — MCP의 4가지 장점: (1) 표준 — 시스템마다 별도 통합 X. (2) 보안 — 표준 권한·인증 패턴. (3) 확장 — 새 시스템 추가 쉬움. (4) 호환 — 챗봇 도구 변경해도 MCP 그대로. 4가지가 ‘본격 사내 도입’ 핵심."),
            ("NOTE", "강사 배경지식 — MCP 없이 통합의 문제: 5개 시스템 (ERP·CRM·메일·CAD·DB) + 챗봇 1개 = 5개 별도 통합. 시스템 변경 시 5개 다 변경. 챗봇 변경 시 5개 다 변경. 운영 부담 큼. MCP — 5개 MCP 서버 + 1 챗봇 표준 클라이언트."),
            ("NOTE", "강사 배경지식 — MCP 지원 도구 현황 (2026.6): (1) Claude 데스크탑 — 공식 1순위. (2) Open WebUI — MCP 지원 (2025). (3) Cursor·VS Code Continue — 개발 도구. (4) Dify — MCP 지원. (5) LibreChat — 일부 지원. ‘우리 챗봇이 MCP 지원하는가’가 도구 선택의 기준."),
            ("NOTE", "강사 배경지식 — MCP의 한국 회사 적용 시점: 2024.11 출시 → 2025 안정화 → 2026.6 본격 적용 권장. ‘초기 시점’이라 ‘작게 시작 → 단계별 확장’ 권장. 본 강좌 작성 2026.6 기준 ‘MCP 시작 적기’."),
            ("Q", "예상 청중 질문 1: ‘MCP 없으면 우리 챗봇 사용 X?’ → 답: ‘아니. RAG + UI로 충분한 회사 다수. MCP는 ‘외부 시스템 데이터 직접 호출 필요’ 시.’"),
            ("Q", "예상 청중 질문 2: ‘MCP는 너무 신규라 위험?’ → 답: ‘2026.6 안정화 단계. 단 ‘본격 운영’보다 ‘1~2 시스템 시작’ 권장. 6개월 안정 후 확장.’"),
            ("Q", "예상 청중 질문 3: ‘MCP 직접 구현 vs 도구?’ → 답: ‘도구 권장. Open WebUI·Claude Desktop이 MCP 클라이언트 자동. 우리는 ‘MCP 서버’만 만들면 됨.’"),
            ("TIP", "강사 함정 — MCP ‘만능’ X: ‘RAG로 충분한 회사 다수’. MCP는 ‘외부 시스템 필수’ 시."),
            ("TIP", "강사 진행 팁 — 6분 시간 배분: 0~1분 USB-C 비유. 1~2분 ‘없으면 vs 있으면’. 2~3분 오픈 표준. 3~4분 채택 현황. 4~5분 4대 장점. 5~6분 청중 질문. 비유 적극."),
            ("BRIDGE", "“MCP 풀이 봤다면 — 아키텍처 디테일.”"),
         ]),
    dict(no=25, lesson="3강", cat="MCP ARCHITECTURE", lay="bullets",
         headline="MCP 아키텍처 — Client · Server · Tools · Resources",
         sub="🟦 불변층 — 4대 구성 요소",
         bullets=[
            "★ Client — 챗봇·AI 앱 (Claude Desktop·Open WebUI 등)",
            "★ Server — 우리가 만드는 ‘각 시스템 연결자’",
            "★ Tools — 서버가 제공하는 ‘함수’ (예: ‘오늘 매출 조회’, ‘이메일 전송’)",
            "★ Resources — 서버가 제공하는 ‘읽기 데이터’ (예: 사내 위키)",
            "★ 통신 — JSON-RPC (가벼운 표준 메시지)",
            "★ 로컬 STDIO 또는 원격 HTTP/SSE — 두 옵션"],
         time="6분 · 아키텍처",
         notes=[
            ("SAY", "“MCP 아키텍처 4대 요소. Client·Server·Tools·Resources.”"),
            ("SAY", "“Client — 챗봇·AI 앱. Claude Desktop·Open WebUI 같은 도구. MCP 클라이언트 자체 구현.”"),
            ("SAY", "“Server — 우리가 만드는 ‘각 시스템 연결자’. ERP MCP 서버, 메일 MCP 서버 식. 각 시스템마다 1개. Python·Node.js·Rust로 개발.”"),
            ("SAY", "“Tools — 서버가 제공하는 ‘함수’. 예 — ‘오늘 매출 조회’, ‘이메일 전송’, ‘회의 일정 잡기’. 챗봇이 호출.”"),
            ("SAY", "“Resources — 서버가 제공하는 ‘읽기 데이터’. 예 — 사내 위키 페이지, 정책 문서. 챗봇이 참고.”"),
            ("SAY", "“통신 — JSON-RPC. ‘가벼운 표준 메시지’. 챗봇 → 서버 ‘이 함수 실행해줘’ 요청 → 서버 응답 → 챗봇이 답에 활용.”"),
            ("SAY", "“연결 방식 — (1) 로컬 STDIO (Standard Input/Output) — 같은 PC. (2) 원격 HTTP/SSE — 별도 서버. 한국 회사 도입 — 사내 별도 서버에 MCP 서버 운영 (원격 HTTP/SSE).”"),
            ("STORY", "MCP SDK 출처. Anthropic 공식 SDK — Python·TypeScript·Rust·Java·Kotlin. URL: modelcontextprotocol.io. ‘하루에 MCP 서버 만들기’ 가능. 한국어 가이드 점점 풍부."),
            ("STORY", "Tools vs Resources (강사 대응용). Tools = ‘함수 호출’ — 동작 수행 (이메일 전송, DB 조회). Resources = ‘데이터 읽기’ — 변하지 않는 정보 (정책 문서, 매뉴얼). 보통 Tools 위주, Resources는 RAG 보조."),
            ("STORY", "JSON-RPC 풀이 (강사 대응용). ‘JSON 형식의 원격 함수 호출’. {“method”: “get_sales”, “params”: {“date”: “2026-06-08”}} 같은 메시지. 가벼움 + 표준. HTTP보다 단순."),
            ("STORY", "STDIO vs HTTP/SSE 선택 (강사 대응용). STDIO — 같은 PC, 빠름, 보안 우수 (외부 X). HTTP/SSE — 별도 서버, 다중 사용자, 확장. 사내 ‘여러 직원 챗봇 사용’ — HTTP/SSE."),
            ("NOTE", "★ 강사 핵심 배경지식 — MCP 4대 요소의 ‘직원 사용 흐름’: (1) 직원이 챗봇에 ‘오늘 매출?’ 입력. (2) 챗봇(Client) → LLM에 묻기 + ‘ERP MCP 서버에 get_sales 호출’ 요청. (3) ERP MCP 서버(Server)가 Tool 실행 → ERP DB 조회 → 결과 반환. (4) 챗봇이 ‘오늘 매출 ___만원’ 답 생성. 자연스러운 흐름."),
            ("NOTE", "강사 배경지식 — MCP 서버 개발 비용 (강사 대응용): 단순 MCP 서버 (5~10 Tools) — 1~2주. 본격 ERP MCP — 1~2개월. 외주 비용 — 100~500만 원 (Python 개발자). 사내 개발자면 무료."),
            ("NOTE", "강사 배경지식 — MCP 서버 ‘우선순위’ 결정: (1) 가장 자주 사용 시스템 — ERP·메일·캘린더. (2) 가장 가치 큰 시스템 — 매출·고객 데이터. (3) 가장 변동 적은 시스템 — 정책 문서·매뉴얼. 우선순위 1~3 시스템부터."),
            ("NOTE", "강사 배경지식 — MCP의 ‘Read-only vs Action’ 분리: 안전 우선 — 첫 시작 MCP는 ‘읽기 전용’ (조회만). ‘이메일 전송·일정 변경 같은 동작’은 보안 검증 후 추가. 첫 사고 위험 낮춤."),
            ("Q", "예상 청중 질문 1: ‘MCP 서버 직접 개발?’ → 답: ‘공식 SDK + 한국어 가이드. 사내 Python 개발자면 1주 학습 + 1주 개발 = 2주. 외주도 가능.’"),
            ("Q", "예상 청중 질문 2: ‘기존 ERP API 그대로 MCP 변환?’ → 답: ‘MCP 서버가 ‘기존 API를 표준 MCP Tools로 감싸기’. ERP 코드 변경 X — MCP 서버가 ‘번역기’.’"),
            ("Q", "예상 청중 질문 3: ‘공식 MCP 서버 사용 가능?’ → 답: ‘Anthropic 공식 서버 50+ 있어요. Filesystem·GitHub·Slack·Postgres 등. ‘ERP·CAD·국내 메일’ 같은 한국 시스템은 직접 개발.’"),
            ("TIP", "강사 함정 — JSON-RPC 깊은 디테일 X: ‘아키텍처만’."),
            ("TIP", "강사 진행 팁 — 6분 시간 배분: 0~1분 4대 요소. 1~3분 각 디테일. 3~4분 통신·연결. 4~5분 ‘직원 사용 흐름’. 5~6분 청중 질문."),
            ("BRIDGE", "“아키텍처 봤다면 — 공식 MCP 서버 + 한국 시스템 연결.”"),
         ]),
    dict(no=26, lesson="3강", cat="MCP SERVERS", lay="stats",
         headline="공식 MCP 서버 + 한국 시스템 연결",
         sub="🟨 가변층 — 2026.6 기준, 매월 새 서버",
         stats=[("공식 — Anthropic 50+",
                 "범용 서버",
                 "Filesystem·GitHub·Slack·Postgres·Gmail·Google Drive·Brave Search 등. 즉시 사용. URL: github.com/modelcontextprotocol/servers."),
                ("한국 ERP",
                 "더존·SAP·자체 ERP",
                 "공식 X. 직접 개발 1~2개월. 더존 ERP REST API 감싸기. SAP은 BAPI 또는 OData. 일반 사내 ERP는 DB 직접 조회."),
                ("한국 메일·캘린더",
                 "Outlook·Microsoft 365·Gmail",
                 "Microsoft 365 — Microsoft Graph API + MCP 서버 (공식 또는 직접). Gmail — 공식. 네이버 메일·다음 — 직접 개발."),
                ("CAD·문서 시스템",
                 "AutoCAD·SolidWorks·문서 DB",
                 "CAD 직접 연결은 복잡. 일반 — ‘CAD 파일 메타데이터 조회’ 정도. 사내 문서 DB — Postgres MCP 사용 가능.")],
         bullets=[], time="6분 · MCP 서버",
         notes=[
            ("SAY", "“공식 + 한국 시스템 MCP 서버 4가지 카테고리.”"),
            ("SAY", "“공식 — Anthropic 50+. URL: github.com/modelcontextprotocol/servers. Filesystem·GitHub·Slack·Postgres·Gmail·Google Drive 즉시 사용. 1시간 설치.”"),
            ("SAY", "“한국 ERP — 공식 X. 직접 개발. (1) 더존 ERP — REST API 감싸기. (2) SAP — BAPI 또는 OData. (3) 자체 ERP — DB 직접 조회. 1~2개월.”"),
            ("SAY", "“한국 메일·캘린더 — (1) Microsoft 365 — Microsoft Graph + MCP 서버. (2) Gmail — Anthropic 공식. (3) 네이버·다음 메일 — 직접. 1주~1개월.”"),
            ("SAY", "“CAD·문서 시스템 — AutoCAD·SolidWorks 직접 연결 복잡. ‘CAD 파일 메타데이터 조회’ 정도. 사내 문서 DB — Postgres MCP.”"),
            ("STORY", "Anthropic 공식 MCP 서버 (강사 대응용). 50+ 서버. URL: github.com/modelcontextprotocol/servers. 카테고리 — (1) 데이터 — Filesystem·Postgres·SQLite. (2) 검색 — Brave Search·Google Drive. (3) 협업 — GitHub·Slack·Gmail. (4) 기타 — Time·Memory·Sequential Thinking. 한국 회사 ‘영어권 도구’ 활용 가능."),
            ("STORY", "한국 ERP 시장 (강사 대응용). 더존 (한국 1위), 영림원, SAP, Oracle 등. 더존 ERP는 ‘REST API’ 제공 — MCP 서버 개발 용이. SAP은 ‘BAPI·OData’ 복잡. 자체 ERP — 회사별 다름."),
            ("STORY", "Microsoft Graph 풀이 (강사 대응용). Microsoft 365 통합 API. 메일·캘린더·OneDrive·Teams 통일. ‘MS Graph + MCP 서버’ 조합으로 ‘Microsoft 365 전체 챗봇 연결’ 가능. 한국 회사 Microsoft 365 사용 다수 → MCP 가치 큼."),
            ("STORY", "한국 회사 MCP 도입 사례 (강사 대응용 추정). 2026.6 시점 한국 MCP 도입 회사 아직 적음. 초기 도입 — (1) 카카오·네이버 일부 사내 — Slack·GitHub·Postgres 공식 서버 활용. (2) 일부 IT 스타트업 — 사내 DB·메일 MCP. (3) 본격 도입은 2026 후반 예상."),
            ("NOTE", "★ 강사 핵심 배경지식 — MCP 서버 우선순위 추천: (1) 첫 시작 — Anthropic 공식 (Postgres·Filesystem·GitHub) — 즉시. (2) 6개월 — 사내 메일 (Microsoft Graph or Gmail) — 자주 사용. (3) 1년 — 사내 ERP — 본격 가치. 단계별."),
            ("NOTE", "강사 배경지식 — ‘공식 서버 그대로 사용 어려운’ 경우: 공식 Gmail MCP — 한국 회사 Microsoft 365 사용 시 ‘Microsoft 365 MCP’ 별도. 공식 Postgres — 사내 ‘회사 MySQL’ 사용 시 ‘MySQL MCP’ 별도 개발. ‘공식 = 즉시 가능’과 ‘사내 도구 다름’ 사이 간극."),
            ("NOTE", "강사 배경지식 — MCP 서버 개발 ‘5분 데모’: ‘우리 회사 매출 조회 MCP 서버’ — Python SDK + 5~10줄 코드. ‘ERP DB 연결 + SELECT 쿼리 + 결과 반환’. 5분에 데모 가능. 본격 운영은 ‘권한·캐싱·에러 처리’ 추가."),
            ("NOTE", "강사 배경지식 — 한국 CAD 시스템 연결: AutoCAD·SolidWorks는 ‘디자인 도구’ — 자동화 어려움. 가능 — ‘CAD 파일 메타데이터’ (파일명·작성자·날짜·버전) 조회. 본격 ‘CAD 데이터 자체 처리’는 본 강좌 외 R&D."),
            ("Q", "예상 청중 질문 1: ‘우리 회사 가장 먼저 무엇?’ → 답: ‘일반 회사 — Microsoft 365 메일 + 캘린더. ‘챗봇이 다음 회의 알려줘’, ‘김 부장께 메일 보내’ 자연. IT 회사 — GitHub·Slack 공식 즉시.’"),
            ("Q", "예상 청중 질문 2: ‘ERP 직접 연결 위험?’ → 답: ‘위험. 읽기 전용 시작. 쓰기 (예: 발주) 절대 X 초기. 6개월 안정 후 ‘소규모 쓰기’ 검토.’"),
            ("Q", "예상 청중 질문 3: ‘MCP 서버 외주 개발?’ → 답: ‘가능. 한국 개발자 — Python·MCP SDK 1주 학습 + 1주 개발 = 견적 100~300만 원. ‘우리 시스템 잘 아는 사내 개발자’가 더 좋음.’"),
            ("TIP", "강사 함정 — ‘MCP 서버 다 직접 개발’ 압박 X: ‘공식 서버부터’ 메시지."),
            ("TIP", "강사 진행 팁 — 6분 시간 배분: 0~1분 4 카테고리. 1~4분 각 1분씩. 4~5분 도입 우선순위. 5~6분 청중 질문."),
            ("BRIDGE", "“MCP 서버 봤다면 — 보안. 권한·감사·격리.”"),
         ]),
    dict(no=27, lesson="3강", cat="MCP SECURITY", lay="bullets",
         headline="MCP 보안 — 권한 · 감사 · 격리",
         sub="🟦 불변층 — 외부 시스템 연결의 위험 + 대응",
         bullets=[
            "★ 위험 — ‘챗봇이 ERP 발주 자동’ 같은 자율 동작 사고 가능",
            "★ 권한 — MCP Tool마다 RBAC. ‘일반 직원 X 매출 조회’ 식",
            "★ 감사 — 모든 MCP 호출 기록 (2편 3강 ELK Stack)",
            "★ 격리 — MCP 서버를 ‘자체 호스팅 sandbox’ 안에 (Anthropic 2026)",
            "★ Read-only 시작 — 첫 도입 ‘조회만’, 6개월 후 ‘쓰기 검토’",
            "★ 사용자 확인 — ‘이 이메일 보낼까요?’ 같은 사전 확인 필수"],
         time="6분 · MCP 보안",
         notes=[
            ("SAY", "“MCP 보안 — 외부 시스템 연결의 위험. 권한·감사·격리 3대.”"),
            ("SAY", "“위험 — ‘챗봇이 ERP 발주 자동’, ‘메일 자동 전송’, ‘DB 자동 삭제’ 같은 자율 동작 사고. ‘직원 실수 한 줄 → 회사 큰 손해’.”"),
            ("SAY", "“권한 — MCP Tool마다 RBAC. ‘일반 직원 — 매출 조회 X. 임원만’, ‘인사 데이터는 HR만’ 식. 2편 3강 RBAC 적용.”"),
            ("SAY", "“감사 — 모든 MCP 호출 기록. ‘누가·언제·어떤 Tool·어떤 결과’. 2편 3강 ELK Stack 동일. 사고 추적 + 패턴 감지.”"),
            ("SAY", "“격리 — MCP 서버를 ‘자체 호스팅 sandbox’ 안에. Anthropic 2026 ‘Managed Agents self-hosted sandbox’ 옵션 활용. 외부 침입자가 사내 다른 시스템 접근 차단.”"),
            ("SAY", "“Read-only 시작 — 첫 도입 ‘조회만’. 6개월 안정 후 ‘쓰기 검토’. ‘메일 자동 전송’ 같은 동작은 마지막에.”"),
            ("SAY", "“사용자 확인 — ‘이 이메일 보낼까요? (예/아니오)’ 같은 사전 확인 필수. 자율 동작 = 위험. 사용자 승인 = 안전.”"),
            ("STORY", "MCP 보안 사례 (강사 대응용). 2025 일부 회사 — MCP 서버에 ‘DB 삭제 권한’ 부여 → 챗봇이 사용자 ‘오래된 데이터 정리’ 요청 → ‘전체 삭제’ 사고. 이후 ‘쓰기 권한 차단’ + ‘사용자 확인’ 의무화. 본 강좌 9편(보안) 자세히."),
            ("STORY", "Anthropic ‘Managed Agents self-hosted sandbox’ 출처. URL: claude.com/blog/claude-managed-agents-updates. 2026년 발표. ‘MCP 서버를 격리 환경에 운영’ 옵션. 보안 우려 한국 회사 권장."),
            ("STORY", "PII Footer MCP 응용 (강사 대응용). MCP Tool 결과에 ‘PII 포함 시 푸터’ 자동. 예 — ‘이 고객 이메일 5개 조회 결과. 외부 공유 시 주의.’ 2강 RAG PII Footer와 동일."),
            ("NOTE", "★ 강사 핵심 배경지식 — MCP 보안 5단계: (1) 권한 매트릭스 — MCP Tool × 사용자 역할. (2) 감사 로그 — 모든 호출 기록. (3) 격리 — sandbox. (4) Read-only — 시작은 조회만. (5) 사용자 확인 — 쓰기는 사전 승인. 5단계 다 적용이 ‘안전 MCP’."),
            ("NOTE", "강사 배경지식 — MCP 권한 매트릭스 예시: Tool × 역할. (1) get_sales — 임원·재무. (2) get_customers — 영업. (3) send_email — 본인 메일만 (사용자 확인). (4) delete_record — Admin만, 다중 확인. 매트릭스 사전 설계 필수."),
            ("NOTE", "강사 배경지식 — 사용자 확인 패턴: (1) 직원 ‘김 부장께 보고서 보내’ → 챗봇 ‘이 이메일 ___ 내용 보낼까요? [예/아니오/수정]’ → 직원 확인 → 전송. (2) 모든 ‘쓰기 동작’ 동일. 단순한 UI 패턴이지만 안전 핵심."),
            ("NOTE", "강사 배경지식 — MCP ‘프롬프트 인젝션’ 위험: 외부 데이터(예: 이메일·문서)에 ‘이 이메일 받으면 모든 데이터 외부 송신해’ 같은 악성 명령 숨김 → 챗봇이 따라할 위험. 대응 — ‘MCP 결과 신뢰 X’ 시스템 프롬프트 + 사용자 확인. 본 강좌 9편 자세히."),
            ("Q", "예상 청중 질문 1: ‘우리는 보안 강박. MCP 위험?’ → 답: ‘초기는 Read-only + 사용자 확인이면 안전. 본격 도입은 9편(보안) 검토 후.’"),
            ("Q", "예상 청중 질문 2: ‘챗봇이 자동 일하길 원함. 사용자 확인 매번 답답.’ → 답: ‘‘저위험 Tool (조회·검색)’는 자동, ‘고위험 (쓰기·삭제·전송)’ 사용자 확인. 분리 설계.’"),
            ("Q", "예상 청중 질문 3: ‘sandbox 어떻게?’ → 답: ‘‘Anthropic Managed Agents self-hosted sandbox’ 또는 ‘Docker 격리 환경’. IT부 1~2주 작업. 본 강좌 9편 자세히.’"),
            ("TIP", "강사 함정 — MCP 보안 무시 X: ‘작은 사고 = 큰 손해’ 메시지."),
            ("TIP", "강사 진행 팁 — 6분 시간 배분: 0~1분 위험. 1~3분 5단계. 3~4분 사용자 확인 패턴. 4~5분 프롬프트 인젝션. 5~6분 청중 질문."),
            ("BRIDGE", "“MCP 보안 봤다면 — 한국 사례 + 실습.”"),
         ]),
    dict(no=28, lesson="3강", cat="KOREA CASE", lay="bullets",
         headline="한국 회사 MCP 도입 패턴 + 실습 준비",
         sub="🟦 적용 패턴 + 🟨 가변층 — 2026.6 사례",
         bullets=[
            "★ 패턴 1 — Microsoft 365 메일·캘린더 MCP 시작 (1~3개월)",
            "★ 패턴 2 — 사내 DB·문서 MCP (Postgres·SQLite) (3~6개월)",
            "★ 패턴 3 — ERP·CRM MCP — 본격 가치 (6~12개월)",
            "★ 패턴 4 — 외부 자동화 (이메일 전송·일정 잡기) — 사용자 확인 (1년+)",
            "★ 우선순위 — 가장 자주 + 가장 안전 (조회) 시작",
            "★ 다음 액션 — IT부 + 챔피언 부서 협업 + 단계 도입"],
         time="5분 · 한국 패턴",
         notes=[
            ("SAY", "“한국 회사 MCP 도입 4가지 패턴 + 우선순위.”"),
            ("SAY", "“패턴 1 — Microsoft 365 메일·캘린더 시작. ‘챗봇이 회의 일정 + 메일 요약 + 답신 초안’. 1~3개월. 즉시 가치.”"),
            ("SAY", "“패턴 2 — 사내 DB·문서 (Postgres·SQLite). ‘챗봇이 사내 매출 DB·고객 DB 조회’. 3~6개월. 본격 RAG 보완.”"),
            ("SAY", "“패턴 3 — ERP·CRM. ‘챗봇이 매출·재고·고객 정보 조회’. 6~12개월. 본격 가치. 직접 개발.”"),
            ("SAY", "“패턴 4 — 외부 자동화. ‘이메일 자동 전송, 일정 자동 잡기, 발주 등’. 사용자 확인 필수. 1년+. 위험 큼.”"),
            ("SAY", "“우선순위 — 가장 자주 + 가장 안전 (조회) 시작. Read-only 패턴 1·2 권장. 패턴 3·4는 단계.”"),
            ("STORY", "한국 사내 MCP 첫 사례 (강사 대응용 추정). 2026년 초 IT·핀테크 일부 회사 ‘Microsoft 365 + GitHub + Postgres’ MCP 도입. ‘챗봇이 회의 안내 + 코드 리뷰 + DB 조회’. 직원 만족도 우수. ‘본격 ERP MCP’는 2026 후반 예상."),
            ("STORY", "한국 MCP 도입 비용 (강사 대응용). (1) 공식 MCP 서버 (메일·DB) — 무료 (Anthropic 공식). (2) 한국 시스템 (ERP) MCP 서버 개발 — 외주 100~500만 원, 사내 무료. (3) MCP 운영 (감사·격리) — 사내 IT 부담. ‘무료~500만 원 + IT 부담’ 시작."),
            ("NOTE", "★ 강사 핵심 배경지식 — 한국 회사 MCP 시작 권장 ‘3단계 12개월 계획’: (1) 0~3개월 — Microsoft 365 메일·캘린더 + GitHub (IT 회사). (2) 3~6개월 — 사내 Postgres·DB. (3) 6~12개월 — 사내 ERP·CRM (조회만). 12개월 후 ‘쓰기·자동화’ 검토."),
            ("NOTE", "강사 배경지식 — MCP 도입 ‘성공 요인 5가지’: (1) IT + 챔피언 부서 협업. (2) Read-only 시작. (3) 사용자 확인 의무화. (4) 감사 로그 처음부터. (5) 6개월 운영 후 단계 확장. 5가지가 안전 도입."),
            ("NOTE", "강사 배경지식 — MCP 안 도입 권장 케이스: (1) 사내 챗봇 첫 시작 + 사용자 10명 미만 — UI·RAG만 충분. (2) 외부 시스템 통합 가치 작음. (3) IT 인력 부족. ‘MCP 안 함’이 답일 수도. ‘RAG로 충분’ 패턴."),
            ("Q", "예상 청중 질문 1: ‘우리는 ERP가 우선 가치인데 6~12개월 너무 길다.’ → 답: ‘ERP 조회만 시작이면 1~3개월 가능. ‘쓰기·자동화’는 12개월+. 가치 큰 ‘조회 Tool 5개’만 우선.’"),
            ("Q", "예상 청중 질문 2: ‘MCP 도입 ROI 어떻게 측정?’ → 답: ‘1편 ROI 측정 방법 — 직원 시간 절감 × 단가. ‘챗봇 회의 안내 5분 → 1분 = 시간당 50만 원 × 일 5분 절감 = 월 100만 원’ 식.’"),
            ("Q", "예상 청중 질문 3: ‘MCP 우리 회사에 안 맞을 수도?’ → 답: ‘있어요. 사내 챗봇 사용량 적거나 외부 시스템 통합 가치 작으면 RAG로 충분. ‘MCP 가치 우선 평가’ 후 결정.’"),
            ("TIP", "강사 함정 — ‘MCP 의무’ X: ‘RAG·MCP 둘 다 가치 있으면 도입, 부족하면 X’."),
            ("TIP", "강사 진행 팁 — 5분 시간 배분: 0~1분 4 패턴. 1~3분 우선순위. 3~4분 ‘안 도입 케이스’. 4~5분 청중 질문."),
            ("BRIDGE", "“3강 마지막 — 실습. 우리 회사 MCP 도입 결정서.”"),
         ]),
    dict(no=29, lesson="3강", cat="WORKSHOP 3", lay="bullets",
         headline="실습 — 우리 회사 MCP 도입 결정서",
         sub="🟦 적용 (워크시트)",
         bullets=[
            "Q1 · MCP 가치 우선 평가 — 사내 시스템 통합 필요한가?",
            "Q2 · 1단계 우선 시스템 — Microsoft 365 / 사내 DB / 다른?",
            "Q3 · Read-only 시작 / 쓰기 포함?",
            "Q4 · 권한·감사·격리 5단계 적용?",
            "Q5 · 도입 일정 — 3개월 / 6개월 / 12개월?",
            "★ 다음 액션 — IT부 + 챔피언 부서 협업, 1단계 시작"],
         time="8분 · 실습",
         notes=[
            ("SAY", "“3강 실습 — MCP 도입 결정서 5칸.”"),
            ("DO", "조별 실습 (5분, 3~4인 1조). Q1~Q5 + 다음 액션."),
            ("SAY", "“권장 시작 — Microsoft 365 메일·캘린더 + Read-only + 5단계 보안 + 3개월. ‘작게 안전 시작’.”"),
            ("Q", "발표 요청: “1단계 우선 시스템.” → 다양."),
            ("NOTE", "★ 강사 핵심 배경지식 — MCP 결정서 5칸 작성 가이드: (1) Q1 — ‘챗봇이 외부 시스템 정보 필요한가’ 솔직히. ‘RAG로 충분’이면 ‘아니오’. (2) Q2 — 가장 자주 + 가장 안전. (3) Q3 — Read-only. (4) Q4 — 5단계 다. (5) Q5 — 3~12개월."),
            ("NOTE", "강사 배경지식 — 다음 주 액션 3가지: (1) MCP 결정서 IT부 + 챔피언 협업. (2) 가장 안전 시작 — Microsoft 365 메일 (1주). (3) 1개월 운영 + 평가. 셋 다 2주 안에."),
            ("Q", "예상 청중 질문 1: ‘우리는 MCP 가치 작음. 도입 X?’ → 답: ‘OK. RAG로 충분이면 MCP 미루기. 6~12개월 후 재평가.’"),
            ("Q", "예상 청중 질문 2: ‘ERP MCP 우선?’ → 답: ‘가능. 단 ‘ERP Read-only 5 Tools’ 정도 우선. ‘쓰기 동작’은 6개월+ 후.’"),
            ("Q", "예상 청중 질문 3: ‘권한 매트릭스 어떻게?’ → 답: ‘‘Tool × 사용자 역할’ 표. 임원·재무·영업·HR·일반 5역할 × Tools. 사내 IT가 매트릭스 작성. 본 강좌 9편 자세히.’"),
            ("TIP", "강사 함정 — ‘완벽 결정 압박’ X."),
            ("TIP", "강사 진행 팁 — 8분 시간 배분: 0~5분 개별. 5~7분 발표. 7~8분 액션."),
            ("BRIDGE", "“3강 + 4편 마무리.”"),
         ]),
    dict(no=30, lesson="3강", cat="PART 4 WRAP", lay="bullets",
         headline="4편 정리 — UI + RAG + MCP 3장",
         sub="🟦 마무리 + 5편 예고",
         bullets=[
            "1강 — UI 결정서 (Open WebUI 95% 권장)",
            "2강 — RAG 설계서 (4단계 + 4계층 + PII Footer)",
            "3강 — MCP 도입 결정서 (Microsoft 365 시작 → ERP)",
            "★ 1~4편 합치면 ‘자체 호스팅 + 사내 챗봇 + 문서 + 시스템 = 10장’",
            "★ 추천 시작 셋 — Open WebUI + Qwen 7B + BGE-M3 + Microsoft 365 MCP",
            "★ 5편(에이전트 기초) — 챗봇이 ‘답하기’에서 ‘일하기’로"],
         time="5분 · 마무리",
         notes=[
            ("SAY", "“4편 마무리. 1·2·3강 동안 UI + RAG + MCP 3장 결정서. 1~4편 = ‘자체 호스팅 + 챗봇 + 문서 + 시스템 = 10장 마스터’.”"),
            ("SAY", "“추천 시작 셋 — Open WebUI + Qwen 7B + BGE-M3 + Microsoft 365 MCP. 4편 완성 후 ‘본격 사내 챗봇’.”"),
            ("SAY", "“다음 주 액션 3가지. (1) 10장 사장님 보고. (2) IT부 + 챔피언 부서 1주 안 Open WebUI 시작. (3) 1개월 후 RAG, 3개월 후 MCP. 단계별.”"),
            ("SAY", "“5편 예고 — ‘에이전트 기초’. 4편이 ‘챗봇 = 답하기’였다면 5편은 ‘에이전트 = 일하기’. 챗봇이 ‘답’에서 ‘실제 업무 수행’ 진화. Claude Code·OpenCode·Cline·Aider 같은 도구 + 4요소.”"),
            ("Q", "발표 요청: “4편 끝나니 우리 회사 챗봇 한 줄 비전?” → 다양."),
            ("NOTE", "★ 강사 핵심 배경지식 — 4편 끝 메시지 톤: ‘1~4편 결정 사라지면 운영 가능’ 안심. 5~11편은 ‘본격 진화’."),
            ("NOTE", "강사 배경지식 — 11편 강좌 위치: 4편 ‘챗봇 본격’. 5~6편 ‘에이전트 기초 + 하네스’. 7~8편 ‘사내 에이전트 + 자체 에이전트’. 9~11편 ‘보안·백업·관리’. 1~4편이 ‘운영 가능 기반’, 5~11편이 ‘본격 진화’."),
            ("TIP", "강사 함정 — ‘완벽 결정 압박’ X."),
            ("TIP", "강사 진행 팁 — 5분 시간 배분: 0~1분 ‘10장 마스터’. 1~2분 ‘추천 셋’. 2~3분 다음 액션. 3~4분 5편 예고. 4~5분 청중 발표."),
            ("BRIDGE", "“4편 끝. 5편 ‘에이전트 기초’에서 챗봇이 ‘일하기’ 진화 봐요.”"),
         ]),
    dict(no=31, lesson="3강", cat="THANKS", lay="title",
         headline="4편 끝 — 5편에서",
         sub="‘에이전트 기초·생태계’로 이어집니다",
         bullets=[], time="3분 · 작별",
         notes=[
            ("SAY", "“4편 마지막 슬라이드입니다. 1·2·3강 180분 고생하셨습니다.”"),
            ("SAY", "“오늘 손에 남은 것 — UI 결정서 + RAG 설계서 + MCP 도입 결정서 = 3장. 1~4편 총 10장. ‘본격 사내 챗봇 운영’ 가능한 마스터 계획.”"),
            ("SAY", "“다음 단계 — 5편 ‘에이전트 기초’. 챗봇이 ‘답하기’에서 ‘일하기’로 진화. Claude Code·OpenCode·Cline·Aider 같은 도구.”"),
            ("SAY", "“오늘 후기·질문은 visionc.co.kr 또는 사내 챔피언과. 다음 시간에 만나요.”"),
            ("NOTE", "★ 강사 핵심 배경지식 — 마무리 톤: 청중 피로 + 칭찬 + 다음 동기."),
            ("TIP", "강사 진행 팁 — 3분 따뜻한 작별."),
            ("BRIDGE", "“감사합니다.”"),
         ]),
    dict(no=32, lesson="3강", cat="THANKS 2", lay="title",
         headline="감사합니다",
         sub="Course 02 · Part 4 · 챗봇·RAG·MCP",
         bullets=[], time="1분",
         notes=[
            ("SAY", "“수고하셨습니다. 5편에서 만나요.”"),
            ("NOTE", "마지막 슬라이드."),
            ("TIP", "1분 안에 작별."),
            ("BRIDGE", "“감사합니다.”"),
         ]),
]

for i, s in enumerate(SLIDES, 1):
    s["no"] = i
TOTAL = len(SLIDES)
